### ISSUE TITLE
Links are not resolved properly

### ISSUE THREAD

**Issue by g12n** [directus/docs#1]
Links between the Documents are not resolved Properly. 

Example: [http://getdirectus.com/docs/getting-started#installation](http://getdirectus.com/docs/getting-started#installation)

![bildschirmfoto 2016-03-31 um 10 54 05](https://cloud.githubusercontent.com/assets/57556/14170603/edf9bfbe-f72e-11e5-86d4-d801ec0ab175.png)

The Requirements-Link ist Pointing to `/docs/docs/1-getting-started/2-requirements.md`
It should simply be Pointing to `#requirements`

I am not sure if this is a this is a Typo in the [03-installation.md](https://github.com/directus/docs/blob/master/01-getting-started/03-installation.md). Or if your publishing tool should catch this automatically. 

Which Site Generator are you Using, to process the documentation?

**Comment by WellingGuzman** [comment]
Hi @g12n, thanks for letting us know,

I worked on the issue and should be fixed by now.

it wasn't a typo, we are using a in-house small script that _generate_ everything, and it didn't have the ability to parse the urls.

Thanks. I'm closing this one, if you spot something else, please open a new ticket.

**Comment by benhaynes** [comment]
Hey @WellingGuzman – not sure if these changes were pushed to the server, but the links on Marketing still aren't working:

http://getdirectus.com/docs/getting-started#requirements

**Click on "Help" link...**

**Comment by WellingGuzman** [comment]
@benhaynes It should be fixed now I was so wrong, I was testing on github itself than the site. let me know if it all fixed. http://getdirectus.com/docs/getting-started#requirements

**Comment by benhaynes** [comment]
Yeehaw – much better

**Comment by g12n** [comment]
I am so sorry! But there is still a glitch:

In the section [Installation](http://getdirectus.com/docs/getting-started#installation) the link to the link to the section requirements doesn't work. 

| generated url |  `http://getdirectus.com/docs/getting-started#/02-requirements`  | 
| ---| ---: |
| sould be | `http://getdirectus.com/docs/getting-started#requirements` |

**Comment by WellingGuzman** [comment]
Hey @g12n, thanks for keeping an eye on this one. I spotted the mistake, hopefully this one will fix the problem. http://getdirectus.com/docs/getting-started#installation

**Comment by g12n** [comment]
Looks good!

While testign I stumbled over a typo causing a bad link. 
This one should fix it: https://github.com/directus/docs/pull/3

It's the ** Learn More ** link in the [Users & Groups](http://getdirectus.com/docs/user-guide#users-and-groups) section.
