### ISSUE TITLE
Docs Next

### ISSUE THREAD

**Issue by phazonoverload** [directus/docs#1]
This project fully overhauls our documentation content, structure, and platform. Tracking progress of content and structure is happening in an internal project board, but this issue will house the platform requirements for launch. 

We will also link existing documentation issues here once they have been included in updated content.

This new docs platform will be served from directus.io/docs

```[tasklist]
- [ ] https://github.com/directus/docs/issues/2
- [ ] https://github.com/directus/docs/issues/3
- [ ] https://github.com/directus/docs/issues/4
- [ ] https://github.com/directus/docs/issues/5
- [ ] https://github.com/directus/docs/issues/6
- [ ] https://github.com/directus/docs/issues/7
- [ ] https://github.com/directus/docs/issues/8
- [ ] https://github.com/directus/docs/issues/9
- [ ] https://github.com/directus/docs/issues/10
- [ ] https://github.com/directus/docs/issues/11
- [ ] https://github.com/directus/docs/issues/12
```

**Comment by rijkvanzanten** [comment]
(FWIW you can't "close" an issue from another issue automatically as you can with PRs 🙂  Not sure if that was the intention here 👍🏻 Changed it to a "Related" tasklist instead)

**Comment by phazonoverload** [comment]
It was, but the related list is absolutely fine. I just wanted to track what's being covered as we do it.

**Comment by alexchopin** [comment]
Moved on Linear
