### ISSUE TITLE
Docs: Custom Input Field Validation

### ISSUE THREAD

**Issue by erondpowell** [directus/docs#10]
https://github.com/directus/directus/discussions/11504

Explain how to customize input field validation logic.
Waiting for https://github.com/directus/docs/issues/101

**Comment by erondpowell** [comment]
@rijkvanzanten Seems like a discussion, which should probably be "dynalinked"... 
I could technically write a guide, but looking now, I think that may be a bit more than necessary for this.

**Comment by rijkvanzanten** [comment]
Works for me 👍🏻

**Comment by rijkvanzanten** [comment]
Linear: DOCS-10
