### ISSUE TITLE
Optimize docs videos playback

### ISSUE THREAD

**Issue by erondpowell** [directus/docs#100]
Currently, all docs videos on a given page play at the same time. 
We want to add a snippet to make just the one onscreen play.

> Interesting @azrikahar @br41nslug, you'd expect browsers to be better at GPU management for inline playing vids that aren't actually being displayed. Adding a bit of JS to automagically stop those vids when they're outside of the viewport makes sense to me, though we have to be careful with re-registering those observers on page transitions (as the docs website is effectively a SPA)

_Originally posted by @rijkvanzanten in https://github.com/directus/docs/issues/97#issuecomment-1218055464_

**Comment by rijkvanzanten** [comment]
Linear: DOCS-29
