### ISSUE TITLE
docs/extensions/pages.md out of date, new system undocumented.

### ISSUE THREAD

**Issue by SharkWipf** [directus/docs#103]
As per directus/directus#2301,

The documentation in [extensions/pages.md](https://github.com/directus/docs/blob/master/extensions/pages.md) provides instructions for the master branch of the directus/api repo, but since tag 2.0.0 of said repo, this is no longer accurate.
The new system seems to be entirely undocumented (and the demo code minified/unformatted, which isn't helping either).
This probably also applies to the rest of the extension documentation, although I don't need those so I haven't looked at those.

**Comment by benhaynes** [comment]
@rijkvanzanten — could you add some insight here? I am not sure what needs to be updated... but the Page Extension Docs _seem_ accurate to me. Thoughts?

**Comment by rijkvanzanten** [comment]
> but since tag 2.0.0 of said repo, this is no longer accurate.

Funnily enough, the docs were written alongside of the 2.0.0 release, so they're all accurate.

The tricky part is the build setup. I wanna fix https://github.com/directus/app/issues/1242 by making a new build chain, publish the buildchain to NPM and add that to the docs.

**Comment by rijkvanzanten** [comment]
We have a dedicated extension toolkit on the github organization now to make this easier. extensions pages have since been addressed
