### ISSUE TITLE
docs: document default storage path

### ISSUE THREAD

**Issue by steebchen** [directus/docs#106]
The default storage path for the local adapter should be documented somewhere, probably in https://github.com/directus/docs/blob/master/advanced/api/configuration.md#storage at the field `root`.

I had to search way too long for this, I ended up checking directus/docker and found out the path is `/var/www/html/public/uploads/_/`.

I can send a PR if approved.

**Comment by rijkvanzanten** [comment]
Sounds good!

Feel free to open a PR 🙂

**Comment by steebchen** [comment]
Do you think it would be useful to add a third column `default` to the table, or is this overkill?

**Comment by rijkvanzanten** [comment]
Good question. Only the first four have defaults I think so it might be overkill. That being said, those first 4 do have defaults that are important to know. 

It's your call!
