### ISSUE TITLE
Docs Overall Cleanup and New Content

### ISSUE THREAD

**Issue by benhaynes** [directus/docs#107]
These are some of the main ideas to accomplish — once one is accepted or big enough we can make a dedicated ticket to track it. ref: @uchilaka

* [ ] Article on SSO
* [ ] Duplicate and update v6 Medium articles for v7

**Comment by uchilaka** [comment]
@benhaynes Hey! I'm back - just put out a PR for a short draft of the setup guidelines you outlined: https://github.com/directus/docs/pull/157. I'll continue working on that and I'll start taking a look at this soon. Will get back to you with any questions I might have on getting started with the cleanup of v6 -> v7 (or would you rather start with SSO?).

**Comment by benhaynes** [comment]
Whichever you prefer!

Also, I just cleaned up and merged your Docs update... thanks!
https://github.com/directus/docs/blob/master/getting-started/setup-checklist.md

**Comment by rijkvanzanten** [comment]
We have a reference on the sso flow now. New articles are now on blog.directus.io
