### ISSUE TITLE
Where I can configure Field Layout

### ISSUE THREAD

**Issue by matchish** [directus/docs#113]
Can't find where I can configure field layout to group or change size, a position the one https://docs.directus.io/guides/fields.html#field-layout

**Comment by benhaynes** [comment]
As of now this has to be done in the database directly (unfortunately), but we're working on a new form grid system that will allow this to be elegantly managed within the App.

https://github.com/directus/app/issues/773
https://github.com/directus/app/issues/1236

**Comment by matchish** [comment]
@benhaynes Thanks for the help. Is there any example how it should be stored in DB?

**Comment by benhaynes** [comment]
Right now, it's 1-4 for `directus_fields.width` — though that will be changing in the future. Groups are an interface right now... which we're working on documenting in the next week or two (along with _all_ interfaces).
