### ISSUE TITLE
Is there a possibility to insert into another table something, when executing a filter hook

### ISSUE THREAD

**Issue by andriipol** [directus/docs#117]
I want to change the status(true) of one raw in the table and simultaneously change a counter of it in another table. Can I implement it in the filter hook?

Thanks in advance

**Comment by benhaynes** [comment]
This seems more like an action hook, but either way you should be able to run any custom code you need on these events:

https://docs.directus.io/extensions/hooks.html#action-hooks

**Comment by andriipol** [comment]
Thanks
