### ISSUE TITLE
Small typo in documentation at hooks#action-hooks

### ISSUE THREAD

**Issue by alanford123** [directus/docs#118]
There's a small typo, it says "pesudo" instead of "pseudo"

hyperlink to the error: https://docs.directus.io/extensions/hooks.html#action-hooks
code example with title 

> Example (Function) In this example we'll notify an admin user everytime a new article is created.

`'hooks' => [
  'actions' => [
    'item.create.articles' => function ($data, $collectionName) {
      $content = 'New article was created with the title: ' . $data['title'];
      **// pesudo function**
      notify('admin@example.com', 'New Article', $content);
    }
  ]
]
`

**Comment by alanford123** [comment]
hyperlink to an image: http://prntscr.com/mx0n4d

**Comment by benhaynes** [comment]
fixed by https://github.com/directus/docs/commit/2f7263191884168a1ede594c3ad63957e911a5f6

**Comment by benhaynes** [comment]
Thanks!

**Comment by benhaynes** [comment]
In the future, there's an edit button at the bottom of the page :)
