### ISSUE TITLE
Docs repo relics

### ISSUE THREAD

**Issue by erondpowell** [directus/docs#124]
I've noticed `index.d.ts` in the main dir seemed to have migrated from vuepress somehow. 
I'm wondering if this is still relevant or a relic or if we have any other relics 🤔

**Comment by rijkvanzanten** [comment]
That's not a relic! That's the (correct) typings for the markdown distribution that goes to `npm`

**Comment by rijkvanzanten** [comment]
I don't think there's any relics. The VitePress branch was completely empty, and we copy pasted in parts of `main` at the time to construct the final version. As far as I can tell, everything in the repo is there on purpose 👍🏻
