### ISSUE TITLE
Detail query parameters in JS-SDK more.

### ISSUE THREAD

**Issue by shealavington** [directus/docs#128]
A question I've come across too many times is people not understanding how to use the query parameters through the JS-SDK, perhaps we could have a section under the SDK on how to use these parameters in the SDK. (Referencing the API-Reference to show what parameters are available)

Perhaps explaining what should be a CSV string (fields), what should be an object (filters), etc.

> With the SDK is it possible to do the *.* depth stuff?
<sub>[View in Slack](https://rangerstudio.slack.com/archives/CDVJD9M1B/p1554818521235200)</sub>

🐰

**Comment by rijkvanzanten** [comment]
> Perhaps explaining what should be a CSV string (fields), what should be an object (filters), etc.

That shouldn't even matter 😄 

```
{
  filter: {
    name: {
      eq: "Rijk"
    }
  }
}

===

{
  'filter[name][eq]': "Rijk"
}
```

**Comment by shealavington** [comment]
Touché — Still, a question I get asked a lot seems to be how to add filters and query parameters through the SDK. 🤷🏻‍♂️

**Comment by rijkvanzanten** [comment]
This has since been added
