### ISSUE TITLE
Menu Item to "Data Access"

### ISSUE THREAD

**Issue by mvhirsch** [directus/docs#136]
Hi!

I've had problems looking for how to access data tables (for example inside a hook) and found nothing, until I google'd. I found a Stackoverflow answer, pointing to Directus Docs: https://docs.directus.io/api/data.html

Can you please link it in the menu somewhere?
I could provide a PR if you wish, please tell me where this should be linked and I would be happy to serve!

Greets from Austria,
Michael

**Comment by benhaynes** [comment]
Thanks Michael! I moved the file and linked it to the main nav (under advanced). The link in SO will be incorrect now, but I wanted to keep things organized.

https://docs.directus.io/advanced/api/data.html

**Comment by mvhirsch** [comment]
Thank you very much!
