### ISSUE TITLE
Example RegEx for Validation

### ISSUE THREAD

**Issue by mvhirsch** [directus/docs#137]
Hi!

The [User Guide / Fields](https://docs.directus.io/guides/fields.html#_2-set-the-schema-options) mentions validation regex. I was curious enough to give it a try, but it isn't documented about how it must look like. I've found [this old issue](https://github.com/directus/api/issues/130#issuecomment-436593340), telling me to write a PCRE regex, within delimiters like `/`. 

This should be documented in the User Guide, too.
I could add a PR if you wish.

Greets from Austria,
Michael

**Comment by benhaynes** [comment]
Hey @mvhirsch — yeah, the Docs have unfortunately been lacking since our team is so busy. But we'd _love_ any help you can provide! :)

We do have validation, but I don't know if the specific format (or examples) are in the Docs. If you figure it out it'd be great to add though!

**Comment by mvhirsch** [comment]
Since #234 was merged, it's safe to close this one.
Thanks @benhaynes

**Comment by sinky** [comment]
Would be nice to see a hint in the admin interface below the field.

**Comment by benhaynes** [comment]
I've added an example as a placeholder for the input in v9
