### ISSUE TITLE
Auto Generate Vue components docs

### ISSUE THREAD

**Issue by erondpowell** [directus/docs#14]
**origin of issue:**
https://discord.com/channels/725371605378924594/835244612356145167/951117574656106537

**Vue Components Wiki**
https://github.com/directus/directus/wiki/v-input
https://github.com/directus/directus/blob/main/app%2Fsrc%2Fcomponents%2Fv-input%2Fv-input.vue#L94

### Vue Component Docs Generators:
**DocGen**
https://www.npmjs.com/package/vue-docgen-api
https://github.com/vue-styleguidist/vue-styleguidist
https://vue-styleguidist.github.io/docgen/

**Comment by rijkvanzanten** [comment]
Linear: DOCS-12
