### ISSUE TITLE
https://docs.directus.io/extensions/pages.html is out of date (not working with Directus 7)

### ISSUE THREAD

**Issue by banjankly** [directus/docs#148]
I want to create a custom extension page with Directus 7.

The documentation on https://docs.directus.io/extensions/pages.html is out of date. With just the two files I get an error. The page.js file inside my custom directory could not be found.

If I copy the /public/extensions/core/pages/_demo/pages.js to my custom directory I do not get this error anymore. But I can not find any documentation about the page.js file and how it works. (Besides the code is minified)

As far as I understand is the page.vue file is not needed anymore. Instead is the page.js file is responsible for rendering. A documentation or at least some hints how the JS render engine is working would be great.

**Comment by hakkurishian** [comment]
I'm experiencing the same issue. Also I can't find the link to the _demo Page ( the one in the docs is broken).

**Comment by benhaynes** [comment]
@rijkvanzanten — any thoughts on this one?

**Comment by hakkurishian** [comment]
Looks like the docs are now updated and the issue can be closed @benhaynes . I was able to create a basic page using the current docs.

**Comment by benhaynes** [comment]
Nice!!

**Comment by hakkurishian** [comment]
However I realised that I was getting the path "extensions/custom/pages" from the old docs, in the current docs it is still missing.

**Comment by benhaynes** [comment]
OK, then we'll have @directus/api-team take a look at updating the new docs. Thanks!

**Comment by rijkvanzanten** [comment]
Updated it to be modules and up to date
