### ISSUE TITLE
Thumbsmith Not working

### ISSUE THREAD

**Issue by erondpowell** [directus/docs#154]
Thumbsmith is not generating thumbnails for the docs. @br41nslug

**Comment by br41nslug** [comment]
@benhaynes Im getting quota errors for Thumbsmith `{"error":"Payment Required. Maximum quota exceeded."}`.
We may need to look into caching these ourselves so not every share/visit counts as a hit on their API

**Comment by benhaynes** [comment]
Plan updated.
