### ISSUE TITLE
Consider renaming "local install" to "build from source"

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/docs#16]
You could technically install a production environment from source too, but you would have to look at the local install docs to know how. Not the most intuitive thing.

If we make this change, we should add a big red note saying that this is not the recommended way of installing production instances, as you should ideally be using the build branch.

**Comment by benhaynes** [comment]
This work? @rijkvanzanten 

https://docs.directus.io/advanced/source.html

**Comment by rijkvanzanten** [comment]
Looks good to me 😄
