### ISSUE TITLE
Install Directus Suite

### ISSUE THREAD

**Issue by clementbirkle** [directus/docs#161]
Hi,

Directus seems to be nice but I did not arrive to install it with the documentation: https://docs.directus.io/getting-started/installation.html#setup

After install via git (composer and dependencies are ok), I go to /admin and I see the login page, not the installer page.

Maybe is it only possible to install it manually ?https://docs.directus.io/advanced/api/configuration.html#project-config-files

Thank you for your help :)

**Comment by benhaynes** [comment]
It seems that you already have an `/api/config/api.php` file. Once the API sees this file it will no longer ask if you want to install. Perhaps this was generated somewhere along your installation process? Could you confirm if it's there or not?

**Comment by clementbirkle** [comment]
Hi, sorry for my late response.

I haven't this file / directory "/api".

I installed Directus files via this command: git clone https://github.com/directus/directus.git

**Comment by JbalTero** [comment]
I also have this issue. I just followed `https://docs.directus.io/getting-started/installation.html#setup`

When it says "Navigate your browser to the App at /admin", this is what I got:

![image](https://user-images.githubusercontent.com/3615746/61226835-c6bf5f00-a755-11e9-99bf-0910a3dfc33d.png)

**Comment by JbalTero** [comment]
![image](https://user-images.githubusercontent.com/3615746/61227015-12720880-a756-11e9-918d-0669b57cf183.png)

**Comment by rijkvanzanten** [comment]
@JbalTero keep an eye on https://github.com/directus/directus/issues/2405

**Comment by andrenaught** [comment]
I have the same issue. Im running it on nginx using the conf in the docs. I try to go into /admin and the login page just stays, and never redirects to install - the loading spinner just keeps going. I tried to sign in just to see what would happen (obviously theres no accounts yet so it wont go through).
<img width="1279" alt="Screen Shot 2019-07-18 at 11 12 09 PM" src="https://user-images.githubusercontent.com/12690211/61513436-eb177780-a9b1-11e9-91df-9070a43b2cd5.png">

I check the error logs in my nginx server and i see this:
<img width="1219" alt="Screen Shot 2019-07-18 at 11 17 09 PM" src="https://user-images.githubusercontent.com/12690211/61513644-a93b0100-a9b2-11e9-9ac1-e59a2a8b4e5f.png">

Locally, using php -S localhost:9000 it runs fine for me though (tested on two local machines)

**Comment by andrenaught** [comment]
I managed to fix my issue, I went to the [requirements page](https://docs.directus.io/advanced/requirements.html) in the installation docs and installed any missing php extensions i had (by checking phpinfo();), and then updated directory ownership. Restarted nginx and php-fpm, and going to /admin redirected me to installation. So check the requirements page, maybe you're missing something from there.

The commands that specifically did it for me we're
```
sudo apt-get install php-imagick
sudo chown -R www-data:www-data /var/www/[directus folder]/
sudo systemctl restart php7.2-fpm
sudo systemctl restart nginx
```

This is an oversight on my part. since I was able to install it locally with no issues, I became a little careless. It would be nice to make the _detailed_ requirements page be an actual step in the installation page in the docs. Maybe show the actual commands needed for the php extensions installation, it would make it look like a necessary action.

Your issue might be different from mine though.

**Comment by rijkvanzanten** [comment]
> It would be nice to make the detailed requirements page be an actual step in the installation page in the docs.

We want to have a dedicated endpoint that will check if all the requirements and permissions are met, so we can render the list on the actual admin app itself. @directus/api-team How hard would this be to implement? I know we're focussed on bug fixes now but it might be a nice thing to implement next (assuming it's not crazy difficult)

**Comment by benhaynes** [comment]
Ref:

https://github.com/directus/app/issues/860
https://github.com/directus/api/issues/461
https://github.com/directus/api/issues/622

**Comment by andrenaught** [comment]
Sorry to keep this thread going. But to help pinpoint my particular issue I did a fresh install on a new server with the same setup and it seems only this command was necessary.

```
sudo chown -R www-data:www-data /var/www/[directus folder]/ 
```

It fixed the second error ```Uncaught (in promise) TypeError: Cannot read property 'code' of undefined at login.vue:405```. The 500 errors from ```/_/auth``` on the console are supposed to be there on a new install I believe.

Though i'm sure installing all the php extensions could potentially save people from headaches down the line. Unrelated but shouldn't this issue should be on the /app or the /directus github repo?

**Comment by JbalTero** [comment]
To check for the requirements, what I did is removed the vendor folder and did the composer install, I found out there are a lot of missing php extensions that I need to install.

**Comment by benhaynes** [comment]
Once we have a few more bugs squashed, we'll be implementing a "Check Requirements" page which will really help devs identify any missing extensions/libs.

**Comment by rijkvanzanten** [comment]
Rewrote the installation instructions, and added the check requirements page on install
