### ISSUE TITLE
Enabling ssl/tls for pdo-mysql

### ISSUE THREAD

**Issue by hagentnet** [directus/docs#165]
Hello guys!
I need to enable secure protocol remote Directus MySQL DB. How to enable ssl/tls transport in pdo-mysql driver? Is it possible to config in api.php file?

**Comment by benhaynes** [comment]
@bjgajjar — does the API support this? If not we can discuss this on the `api` repo. (I wan't sure if we support it or not)

**Comment by hagentnet** [comment]
At the moment I'm trying Directus 7.3.1 Suite and Standalone App.
Running on PHP 7.2 with SSL options like `\PDO::MYSQL_ATTR_SSL_*`
error_log:
```
[23-Jun-2019 19:00:31 UTC] PHP Fatal error:  Uncaught Error: Undefined class constant 'MYSQL_ATTR_SSL_VERIFY_SERVER_CERT' in /public_html/directus/config/api.php:30
Stack trace:
#0 /public_html/directus/src/web.php(38): require()
#1 /public_html/directus/public/index.php(3): require('/...')
#2 {main}
```

**Comment by scottmckenzie** [comment]
I just submitted a PR for this:
https://github.com/directus/api/pull/1295

**Comment by rijkvanzanten** [comment]
This was added to the API

**Comment by hagentnet** [comment]
Great! Will test it ASAP))
