### ISSUE TITLE
Versions & updating "Read how to" link is dead

### ISSUE THREAD

**Issue by Ronnyrr** [directus/docs#17]
On the docs page https://docs.getdirectus.com/6.3.6/#Versions_&_Updating the "Read how to" link is dead. The links points to: https://docs.getdirectus.com/developer-guide/cli.md#database-module

Would like to know how to migrate the database! :)

**Comment by colorando-de** [comment]
Link is still dead. There is currently no information how to update the database. I tried to execute `php ruckus.php db:upgrade -1` what ran through successfully but then leaded to server errors.

**Comment by benhaynes** [comment]
@WellingGuzman or @rijkvanzanten – do we have a plan for updating/parsing these links automatically? Can we at least update this one?

**Comment by WellingGuzman** [comment]
I will dig into the parser to find a way to fix these type of links.

**Comment by WellingGuzman** [comment]
Closed by https://github.com/directus/docs/commit/bfc9c3e8b01e99633570af2eed94d3e02c4f5fed
