### ISSUE TITLE
State of SSO

### ISSUE THREAD

**Issue by erondpowell** [directus/docs#17]
https://github.com/directus/directus/discussions/12443

'Github requires the authenticating user to have their email as public in their settings in order for it to be picked up when authenticating. There might be a way around it by providing the proper grants or scope, but I never found it. That should probably be documented somewhere! 😅'

- [ ] Full Tutorial
As a front-end dev, I've read the documentation, watched the tutorials on Youtube, and am reading the Github issues/discussions, and I still don't know where to start, to create public registration and hopefully Gmail login.

**Comment by rijkvanzanten** [comment]
Linear: DOCS-14
