### ISSUE TITLE
Retrieving file data when getting items in a collection

### ISSUE THREAD

**Issue by koreset** [directus/docs#175]
Hi guys
I created an collection which has one of its fields as a file type. When I GET that item via the API, I get a int as the value of the file field which is fine. However, there any documented way to get the file url, etc without making a secondary call?

For example, I can issue a call to get an item and get a payload like this ...
`{
    "data": [
        {
            "created_on": "2019-07-19 05:30:25",
            "modified_by": 1,
            "modified_on": "2019-07-19 05:30:25",
            "title": "Article One",
            "id": 1,
            "body": "<p>Contrary to popular belief...</p>",
            "status": "draft",
            "main_image": 1,
            "sort": null,
            "created_by": 1
        }
    ]
}`

The main_image field returns the value of 1 which I use to make another call to /files endpoint to get a payload like this...
`{
    "data": {
        "description": "",
        "type": "image/png",
        "width": 1210,
        "charset": "binary",
        "height": 654,
        "embed": null,
        "id": 2,
        "duration": null,
        "folder": null,
        "title": "Background Img 02",
        "filesize": 1067106,
        "storage": "local",
        "filename": "background-img-02.png",
        "uploaded_on": "2019-07-20T14:58:59+00:00",
        "checksum": "46ef0f2f42982e8f579c89f6356a94bc",
        "tags": [],
        "uploaded_by": 1,
        "location": "",
        "metadata": null,
        "data": {
            "full_url": "http://localhost:8080/uploads/_/originals/background-img-02.png",
            "url": "/uploads/_/originals/background-img-02.png",
            "thumbnails": [
                {
                    "url": "http://localhost:8080/thumbnail/_/200/200/crop/good/background-img-02.png",
                    "relative_url": "/thumbnail/_/200/200/crop/good/background-img-02.png",
                    "dimension": "200x200",
                    "width": 200,
                    "height": 200
                }
            ],
            "embed": null
        }
    }
}`

Ideally I would like to be able to get all this data in one go. Is this possible?

**Comment by benhaynes** [comment]
Yeah, use the `?fields=*.*` parameter:

https://docs.directus.io/api/reference.html#fields

**Comment by YamiteruXYZ** [comment]
How?

**Comment by rijkvanzanten** [comment]
@YamiteruXYZ https://docs.directus.io/api/query/fields.html
