### ISSUE TITLE
Install directus suite error

### ISSUE THREAD

**Issue by sharklatan** [directus/docs#177]
I have problems to install on web server (host)
Only show

> Invalid database connection

Apache 2.2.23 
MySQL 5.1.63 | Running
Php 5.2.17 
DirectAdmin 1.53.0 select to PHP 7.1 Alpha

I could only think that it is the mysql version, if so
some version of directus that works in this mysql

![467FB975-820F-4256-A6ED-905E57EF5F7D](https://user-images.githubusercontent.com/5210221/61929023-efa6d780-af3f-11e9-9e33-e4fbbf204b73.j

**Comment by sharklatan** [comment]
![D7D3E4F8-B82F-4BB8-A02F-B5FE350BEAD0](https://user-images.githubusercontent.com/5210221/61929247-807db300-af40-11e9-8d75-fce045e174ed.jpeg)

**Comment by benhaynes** [comment]
Looks like you're running MySQL `5.1.63` but Direcctus requires at least MySQL `5.7`...

https://docs.directus.io/getting-started/installation.html#requirements
