### ISSUE TITLE
NGINX_Configuration

### ISSUE THREAD

**Issue by jokmontoya** [directus/docs#18]
In this section:
https://docs.getdirectus.com/6.3.6/#NGINX_Configuration
I think there is an error in this directive:

> **Extensions**
> 
> To prevent direct access to extensions api.php file we need to edit /etc/nginx/sites-available/default and add a new location:
> 
> ```
> location ~* [^/]+/customs/extensions/api\.php$ {
>     return 403;
> }
> ```

Don't work as intended, it should be:
```
location ~* ^/customs/extensions/api\.php$ {
    return 403;
}

```

**Comment by WellingGuzman** [comment]
Hey @jokmontoya thanks, do you mind to open a PR?

**Comment by jokmontoya** [comment]
Ok, it's done. Thanks for this CMS, it is something I have been long looking for.

**Comment by jokmontoya** [comment]
I have detected another problem in the docs for Nginx configuration:

> Add a new location:
     location /api {
	if (!-e $request_filename) {
		rewrite ^/1/extensions/([^/]+) /api/api.php?run_extension=$1 last;
	}
	rewrite ^ /api/api.php?run_api_router=1 last;
      }

In Nginx if the `last` flag is inside a location it returns a **500** error.
From the Nginx docs:
[Nginx Docs Rewrite module](http://nginx.org/en/docs/http/ngx_http_rewrite_module.html#rewrite)
> But if these directives are put inside the “/download/” location, the last flag should be replaced by break,  or otherwise Nginx will make 10 cycles and return the 500 error:

I tried to replace the `last` flags with `break` as suggested by Nginx docs, but if I use `break` it stops evaluating other locations, then  `location ~ \.php$` is not checked and calls to `/api/` returns the api.php source.

I had fixed it by changing the `run_api_router` `rewrite` for a `try_files` and moving the extensions rewrite outside of the `location` and the`if`. I have not seen any extension example and I don't use any extension, I am not sure if the `if` is really needed.

My solution is this:

```
 rewrite ^/api/1/extensions/([^/]+)  /api/api.php?run_extension=$1 last;

  location   /api {
                        try_files $uri $uri/ /api/api.php?run_api_router=1&$query_string;
                }
```

The first time I omitted the `&$query_string` part and things didn't go well, that's why I opened and closed [this issue in directus](https://github.com/directus/directus/issues/1429)

If you think these changes are ok I can open a PR.

**Comment by WellingGuzman** [comment]
Hey @jokmontoya, is this something they changed in recent versions? I'm curious because it didn't throw me 500 error before **to me**, saying that I'm not experience it.

So if this is something that differ from versions or distribution would be good to point that out in the docs as well.

**Comment by jokmontoya** [comment]
Hi @WellingGuzman, I have reverted my Nginx settings to the same you have in the docs, stopped nginx service and launched nginx-debug service to try to debug the error.

 But now it's working fine, I have reverted to nginx service and is still working fine. I don't know where the problem  was, maybe some other setting in my setup was causing the loop reaching the 10 redirects hard limit in Nginx.

Maybe there is a mistake in the previous note I found in Nginx docs, and it should be "or otherwise Nginx _could_ make 10 cycles" instead of "will make"?

In other places of the docs I have found more references to the 10 internal redirects limit, but as something more general, not related to using that flag inside a location.

> There is a limit of 10 internal redirects per request to prevent request processing cycles that can occur in incorrect configurations. If this limit is reached, the error 500 (Internal Server Error) is returned. ....
[first reference](http://nginx.org/en/docs/http/ngx_http_rewrite_module.html#rewrite)
[second reference](http://nginx.org/en/docs/http/ngx_http_core_module.html#internal)

Sorry for all the fuss around this issue, I took some incorrect assumptions after reading the nginx documents.

But there's something else related to this section of the docs:

I don't have any extension to try it but I don't think this code will ever be executed
```
location /api {
if (!-e $request_filename) {
rewrite ^/1/extensions/([^/]+) /api/api.php?run_extension=$1 last;
}
......
```
If the rewrite is inside this location `/api`, the rewrite pattern `^/1/.....` will never be matched. I think it should be  this '^/api/1/.....`

**Comment by WellingGuzman** [comment]
Hey, sorry for the delay, if you happen to bump into a way to replicate the issue let us know.

About the rewrite it's true, it will never be matched, so I've updated it here: https://github.com/directus/directus-vagrant/commit/c831f4a040b78b69b277977de0f9b8a4e6b044a2
