### ISSUE TITLE
Docs: Extensions Updates

### ISSUE THREAD

**Issue by erondpowell** [directus/docs#18]
Load from NPM
https://github.com/directus/directus/discussions/12408

Customize WYSIWYG
https://discord.com/channels/725371605378924594/741319150030553159/946403336356257822

Currently no docs on defining custom endpoints.
https://github.com/directus/directus/discussions/11632
https://docs.directus.io/extensions/endpoints/

Inaccurate Hooks Description
https://discord.com/channels/725371605378924594/981162066771574784/982007214908796938
https://discord.com/channels/725371605378924594/981162066771574784/982028803306041365

EXTENSION_NAME_REGEX
https://github.com/directus/directus/discussions/14417

Custom Module with Custom Navigation
https://github.com/directus/directus/discussions/13932#discussioncomment-2964330

Custom Migrations
https://github.com/directus/directus/discussions/14826

Get auth user example misleading in SDK
https://github.com/directus/directus/discussions/15306#discussioncomment-3498320

**Comment by rijkvanzanten** [comment]
Linear: DOCS-15
