### ISSUE TITLE
How i can search items using a tag type?

### ISSUE THREAD

**Issue by luizbueno-hotmart** [directus/docs#189]
Hi everyone;

How i can search items using a tag type? Using a array of strings in the "tags" field to find items that contains these tags.

Thank for help!

**Comment by rijkvanzanten** [comment]
The tags type is saved as a string, so you should be able to do any string search within that (for example `contains` with a value).

I'm not too sure how to search for multiple values at the same time though, as the order can be different. You'll probably have to throw in a `logical[or]` statement too (see https://docs.directus.io/api/reference.html#filtering).

So you'll end up with `?filter[tags][contains]=tag-1&logical[tags]=or&filter[tags][contains]=tag-2`

@directus/api-team could you confirm the above syntax?

**Comment by luizbueno-hotmart** [comment]
Hi @rijkvanzanten thanks for your answer.

I've tried to use `logical[or]` but i couldn't get success with them.

We need to use another approach that works.

Thanks for help!

**Comment by malchiste** [comment]
Hi all, 
I am also having issues to filter on tags successfully. 

My problem is one of my tags is a substring of another, how can I ensure I match exactly one tag name.

The tag names I have are: "fruit" & "fresh-fruits" so filtering by [contains]=fruit gets me values with "fresh-fruits".

Any way to match exactly the tag name?

**Comment by benhaynes** [comment]
Hey @malchiste — the tags Interface has a "wrap with delimiter" option you should turn on. Then you can do exact searches for `,fruit,` to only get that tag.

**Comment by malchiste** [comment]
Works like a charm @benhaynes, thanks a lot!

**Comment by rycastaneda** [comment]
does the ,fruit, work from what version onwards? @benhaynes trying this on my end, but its not working

**Comment by benhaynes** [comment]
We've had the "wrap with delimiter" as far back as I remember... and for searching, that's just how SQL works.

**Comment by ashx404** [comment]
I am trying to search with multiple tags. So in my case there is a tags array and I am using [contains] , for 1 tag it shows all the entries with that tag but how do I get entries which have both tags. In docs it is mentioned that chained filters are ANDed by default but in my case it is showing all the entries which contain both the tags. It works fine for other different columns.
?filter[field_name][contains]=tag1&filter[field_name][contains]=tag2
