### ISSUE TITLE
Database Mirroring failure for existing database (help needed)

### ISSUE THREAD

**Issue by MidnightP** [directus/docs#190]
Hi there! Really excited to start using this.

Just creating an issue here because I think it has to do with documentation rather than anything else.

I can't find out how to use Directus on top of an existing DB. I updated the Directus installation in my hosting provider so that it runs with the existing DB credentials. Directus runs fine but everything is empty! How can we use this for our existing data?

Probably just missing some information or can't find it...

**Comment by rijkvanzanten** [comment]
If you go to admin settings, the databases should be visible with a `manage` button next to them. Clicking those will create the appropriate records in `directus_collections` so Directus is able to manage them

**Comment by MidnightP** [comment]
![image](https://user-images.githubusercontent.com/22522186/63197460-26bc6480-c078-11e9-8b8f-b91b953b2dd8.png)

**Comment by rijkvanzanten** [comment]
In the collections & fields section. Btw, you probably wanna update your Directus instance, you're on a very old version 🙂

**Comment by MidnightP** [comment]
Thanks! Can I update with "Update Database RUN SCRIPT" ? Or do I need to start over?

**Comment by MidnightP** [comment]
![image](https://user-images.githubusercontent.com/22522186/63197800-148ef600-c079-11e9-88d2-92a652adfa83.png)

**Comment by rijkvanzanten** [comment]
I don't know how you installed Directus in the first place, so I afraid I can't help you out with that. You can download the latest release from https://github.com/directus/directus/releases

**Comment by MidnightP** [comment]
What about my original question?

**Comment by benhaynes** [comment]
Once you're on the latest version we can help you troubleshoot the other issue. All tables (managed or unmanaged) will show up on that page.
