### ISSUE TITLE
"Interface types"

### ISSUE THREAD

**Issue by justrealmilk** [directus/docs#191]
Much like https://docs.directus.io/guides/field-types.html I think it would be super **helpful to have something similar for Interfaces,** especially when configuring interfaces like the Repeater where you must manually specify field types.

**Comment by benhaynes** [comment]
Yes — absolutely a good idea.

I'll try to find some time to start adding these in tomorrow.

**Comment by benhaynes** [comment]
I've started this here: https://github.com/directus/docs/blob/master/guides/interfaces.md#core-interfaces

It's definitely a work in progress, as there are a lot of interfaces to describe, but I have all interface headers in and a general format. The only thing I'd like to add is a screenshot of the interface.
