### ISSUE TITLE
translation: id comes whole object

### ISSUE THREAD

**Issue by dargains** [directus/docs#198]
Hello, there. 
Using translation relationships I've noticed that while it language_id comes ok (a numeric value), the article_id does not (the api returns the whole article object), rendering the translation unusable. I'have just clone-installed directus on my server.

Am I doing something wrong here? Here are some prints to help.

The translations table gets an object as project_id, thus printing NaN.
![image](https://user-images.githubusercontent.com/16159324/64475284-beddd300-d178-11e9-9814-a586dec80001.png)

Image of the api returning the whole object:
![image](https://user-images.githubusercontent.com/16159324/64475295-e59c0980-d178-11e9-904e-615bd213e60c.png)

I've set up the translation field like this:
![image](https://user-images.githubusercontent.com/16159324/64475313-11b78a80-d179-11e9-8ff6-d7fde4c8ac37.png)

![image](https://user-images.githubusercontent.com/16159324/64475316-18de9880-d179-11e9-9e05-5fb6c267e641.png)

The languages table:
![image](https://user-images.githubusercontent.com/16159324/64475589-a8397b00-d17c-11e9-9288-576f15c5b988.png)

And the relationship table:
![image](https://user-images.githubusercontent.com/16159324/64475604-c8693a00-d17c-11e9-839a-7614fdbee33a.png)

**Comment by dargains** [comment]
Hi guys.
If you're busy right now I can try to have a look around and if I get lucky make a PR.
I'm guessing it's something to do with the foreign key attribution on relational tables, so I'd be most grateful if you could point me to where it gets its values in the code.

Thanks again,

**Comment by benhaynes** [comment]
Hey @dargains — we are pretty busy (client projects) for the next two weeks... then it's full-time Directus!

In the meantime, @rijkvanzanten or @bjgajjar might be able to point you in the right direction. :)

**Comment by bjgajjar** [comment]
Hey @dargains  - Let's connect in our slack [channel](https://directus.chat). You can find me **@binal** over there.

**Comment by bjgajjar** [comment]
@dargains - We can close this on the reference to https://github.com/directus/app/issues/2068.  Right?

**Comment by dargains** [comment]
Have the PR on issue 2068 been merged to master yet? How can I test the fix?

**Comment by bjgajjar** [comment]
@dargains  - It's not merged into `master` yet. But it will be in our next release.  Here is the PR https://github.com/directus/app/pull/2062

**Comment by dargains** [comment]
All right, thanks a lot, @bjgajjar !

**Comment by bjgajjar** [comment]
@benhaynes :bell:

**Comment by benhaynes** [comment]
In the next few days... don't have an exact date yet though.

**Comment by dargains** [comment]
I just confirmed I can now edit translated fields.
Thanks guys for your attention and awesome work!
