### ISSUE TITLE
Proofread and Style Update

### ISSUE THREAD

**Issue by erondpowell** [directus/docs#2]
Waiting for #9 

**TODO:**
- [ ] Directus Taxonomy
- [ ] Proofread
- [ ] Glossary

**Comment by azrikahar** [comment]
@erondpowell I believe the combination of the fairly recent move to Vitepress plus the spellchecker may have addressed this issue! Or are there any other action items to cover here?

**Comment by erondpowell** [comment]
It did not address the issues here. This ticket is about prose, the directus taxonomy, and the way we structure info within each document.

**Comment by rijkvanzanten** [comment]
Linear: DOCS-6
