### ISSUE TITLE
Add information about thumbnailer actions setting

### ISSUE THREAD

**Issue by wellingguzman** [directus/docs#20]
The information for `actions` in `directus_settings` are empty and is currently unclear how can be used by the end user without making it too confusing.

At the moment all this data are to create thumbnail using different mode; `crop` or `contain` using [Intervention Image Library](http://image.intervention.io/).

All these data can be used to create customized thumbnails image.

**Comment by benhaynes** [comment]
Also, make sure to update the dedicated thumbnailer page too

**Comment by rijkvanzanten** [comment]
This has since been added to the docs. See https://github.com/directus/docs/blob/master/guides/thumbnailer.md
