### ISSUE TITLE
How can I create a self relationship?

### ISSUE THREAD

**Issue by gurumark** [directus/docs#202]
1- I am trying to create a self-relationship (O2M). For example, One manager manages many employees and an employee is managed by one manager. Both managers and employees are of employees collection. How can I create this relatioship?
2- How can I put a limit on one direction? For example, one manager can at most manage 10 employees.

Thanks in advance.

**Comment by benhaynes** [comment]
1. This should just be a O2M field (with a name like `staff`) from `employees` to `employees`, and also a M2O field (with a name like `supervisor`) from `employees` to `employees`. 

2. The `one-to-many` interface would need to be extended to support a `max_items` option. This would be used to limit how many items can be selected. This (and `min`) would be a useful addition, so it could be merged into the Core codebase and doesn't need to be a custom extension.

**Comment by gurumark** [comment]
Thanks for the quick response.
2- Is there any possibility that this feature (min-items and max-items) could be included in the next release?
Is it possible to limit the values to certain values by running a SQL?
For example, An employee in Miami can only be managed by a manager in Miami location.

**Comment by benhaynes** [comment]
Our team is in a feature-freeze, so unless a PR was submitted (or sponsored), those new options wouldn't be included for a while.

For limiting vales, you could look into API Hook Filters to potentially augment/validate the values. 

https://docs.directus.io/extensions/hooks.html#reference
