### ISSUE TITLE
Explain how to use the API filters parameter

### ISSUE THREAD

**Issue by Hainesy** [directus/docs#21]
It is not clear from the documentation how to filter results using the querystring "filters" parameter.

**Comment by WellingGuzman** [comment]
We actually don't clear information on how to use it but it boils down to this:

`?filters[column-name][operator]=value`

here is a list of operators

https://github.com/directus/api-docs/blob/bda12a2e2ec0cb8bca2f8b9e499a7e8d3050f7c5/01-overview/04-php-sdk.md#supported-operators

**Comment by WellingGuzman** [comment]
We will be updating the documentation as soon as we finish the next directus release.

**Comment by Hainesy** [comment]
That's all need, thank you!

**Comment by benhaynes** [comment]
Hey – just as an update:

https://github.com/directus/api-docs/blob/master/01-overview/filters.md

We'll make sure this is all pulling into the Web docs soon. Let us know if anything in these docs are unclear and we'll add more info.

**Comment by Hainesy** [comment]
This is helpful. Although obvious to me, it might be worth giving an
example that uses multiple filters, and explain that these are logically
ANDed together.

There's also no indication on how one would format a list for the "in"
operator, or the two values for the "between" operator, and what should be
the value for the "null" or "nnull" operators?

An example for each operator in the table would clarify all of these
questions.

Thanks

Chris

**Comment by benhaynes** [comment]
Absolutely! @WellingGuzman was actually going to add a multiple example, but then we got distracted with other work. We'll do that and the `in` examples today!

**Comment by benhaynes** [comment]
OK, this has been updated!

https://github.com/directus/api-docs/blob/1.1/overview/filters.md

**Comment by Hainesy** [comment]
This is much better. A quick question on the OR filter: is there a way to search for items where either one of two fields matches a text string? I can't would out a way to do it, but it would seem like a fairly basic feature to be able to search e.g. where either the "note" field or the "title" field contain a search string.

**Comment by benhaynes** [comment]
Hey @Hainesy – this example should help you with that one:
https://github.com/directus/api-docs/blob/1.1/overview/filters.md#example-fetching-customers-from-new-york-and-new-mexico-united-states

**Comment by Hainesy** [comment]
That's an OR on the same field. I'm talking about ORing on a different field.

**Comment by WellingGuzman** [comment]
@Hainesy you can use another column, change the column name for the desired one.

Ex:

```
api/1.1/tables/articles/rows?filters[title][contains]=directus&filters[note][logical]=or&filters[note][contains]=directus
```

It will looks for any records in `articles` tables that contains `directus` in either the `title` or the `note` column.

**Comment by Hainesy** [comment]
Yeh I tried that and it didn't work. I'll try again on Monday to double check.

**Comment by Hainesy** [comment]
@WellingGuzman I confirm this doesn't work. I tried `api/1.1/tables/Internal_Notes/rows/?filters[note][contains]=test&filters[title][logical]=or&filters[title][contains]=test` and it only returns matches where the note field contains test.

**Comment by WellingGuzman** [comment]
Hey @Hainesy, did you pull the latest commit?

**Comment by WellingGuzman** [comment]
I will close this ticket as this is working unless a proper schema is provide where we could reproduce this error.

**Comment by Hainesy** [comment]
Apologies, I haven't had time to test with the latest commit. What is the process for upgrading an existing install that wasn't installed from git, but from a downloaded zip?

**Comment by WellingGuzman** [comment]
We do not have any process of doing upgrade rather than good ol' copy and replace.

**Comment by linonetwo** [comment]
Confirmed, it works.

**Comment by rijkvanzanten** [comment]
Hey @linonetwo! We're actually re-doing the API docs for version 7 as we speak. Do you have any recommendations on how this Search chapter could look like? 😄

**Comment by linonetwo** [comment]
I think it can clarify that search in directus is utilizing "filters".

And examples:

Search in a single field is using "contains" filter: `/?filters[field_one_to_search][contains]=${keyWord}`.

Search in multiple field is using "contains" filter and "logical" filters: `/?filters[field_one_to_search][contains]=${keyWord}&filters[field_two_to_search][logical]=or&filters[field_two_to_search][contains]=${keyWord}`.

I got how search in directus works when I understood "contains" filter and "logical" filters!
