### ISSUE TITLE
Server > HealthCheck Link to Draft Spec 404

### ISSUE THREAD

**Issue by ConnorSimply** [directus/docs#211]
The link to the [Health Check Response Format for HTTP APIs Draft Specification](https://tools.ietf.org/id/draft-inadarei-api-health-check-05.html) is outdated and doesn't go to the draft spec.

https://docs.directus.io/reference/system/server.html#health

https://github.com/directus/docs/blob/4c7499c68c8d02795381ab12330c815ba188838e/reference/system/server.md?plain=1#L247

**Comment by azrikahar** [comment]
The updated link should be https://datatracker.ietf.org/doc/html/draft-inadarei-api-health-check-05, if I'm not mistaken (not super familiar with these).

There's also a [6th draft now](https://datatracker.ietf.org/doc/html/draft-inadarei-api-health-check-06) so maybe we can link to it instead, as [the diff to the 5th draft](https://www.ietf.org/rfcdiff?url2=draft-inadarei-api-health-check-06.txt) seems to only be dates. Presumably just as a more "updated" draft.
