### ISSUE TITLE
Better installation instructions 

### ISSUE THREAD

**Issue by Brian-Myers-Bose** [directus/docs#214]
As a novice user, one of the things I’ve noticed to be lacking is install instructions.

In my opinion, installation instruction should not only educate users about concepts, but they should also provide specific, detailed instructions that one can follow exactly without any prior knowledge.  I believe the current install instructions have a few issues here.

1. At least one specific, limited environment install should be present.  This is the basic guide.  It also helps to build confidence in the product when one can go step by step and end up with a positive result.
	a. Can you achieve a clean install without taking any outside knowledge?
	b. Have a nontechnical person attempt an install without any aid.  How did that turn out?
	c. No one ever complained that the instructions were too easy to follow.
	d. Helps to have a guide to the overall flow of an install, and then allow the engineer to complicate it with new variables.

2. The install instructions try to cover too many bases at one time.  Pathways regularly jump between one installation pathway and another.  The dialog appears to be building an image within the user’s mind and then jumps to, “but if you were doing an install in this other place, click here”.  Storing text on a server costs nothing.  So for usability, copy/paste and build out each idea instead of trying to meld them all together.

3. Narrative can not rely on just saying something once.  Repeat yourself often.  Concepts are much easier to grasp if one goes back over key points multiple times.  Conservation of words may be good in programming, but it is terrible for building an image in another person’s head.

I will argue that an AWS EC2 instance is an excellent choice.  
* We know the hardware environment
* We know OS
* We know OS-state
* We can control which libraries are installed and how
* A user can take images along the way to provide a safety net. 
* Anyone else with a little experience who is using a virtual machine environment is used to seeing instructions for deployment on EC2 and can therefore adapt instructions to their needs.

The four instructional standup’s that I personally would want to see here is 
   1. Install from master.zip. 
      a. This is as clean an install as one can do.  
      b. The number of outside systems that must be relied on are limited.
      c. **I am attaching a set of install instructions for this environment that I have prepared.**

   2. Install from git.  This introduces a few new variables.  This is the one I’m currently working on.  The installation instructions for this are not good.  _The worst part is if one wants the community to give back to the project then this pathway should be bulletproof, for it allows programmers to build a development environment in which to play._
   
   3. Install from Docker.
      - This could mature into different levels of building out Docker images.

   4. Kubernettes

On a related note, I have an AMI built using my provided installation instructions.  Has anyone thought to maintain a Directus AMI?  Seems that the ability to go into AWS, search for AMI, and then click "Launch" would be excellent.

[Directus - Installation to share.docx](https://github.com/directus/app/files/3734906/Directus.-.Installation.to.share.docx)

**Comment by Brian-Myers-Bose** [comment]
Attached are installation instructions that cover 

- bringing up an EC2 Instance
- installing Docker
- creating swap space
- git-clone directus-docker
- build base & core
- build api
- build app
- deploy docker containers
- expose EC2 Docker ports to outside world and updating configuration
- creating elastic IPs
- overcoming common problems
- and running Directus
[Directus - Installation From Git to Docker to share.docx](https://github.com/directus/docs/files/3763121/Directus.-.Installation.From.Git.to.Docker.to.share.docx)

@benhaynes Instead of my continuing to add documentation to this thread, should I be placing it somewhere else, or integrating it into some existing documentation as a branch?

**Comment by benhaynes** [comment]
Thanks @Brian-Myers-Bose — the best way to submit new/updated docs would be to create a PR to the master branch, or if you want to have more control, we can create a dedicated branch. Right @rijkvanzanten ?

**Comment by rijkvanzanten** [comment]
Yup!

**Comment by rijkvanzanten** [comment]
Rewrote the installation instructions. they should be way clearer now 🙂
