### ISSUE TITLE
rate_limit cannot be set via the application and any value is set in the databse

### ISSUE THREAD

**Issue by dario30186** [directus/docs#215]
Hi all,
in your documentation you write that we can set rate_limit object when creating a new project.
But how to display existing values and change them for an existing project?
You also write that default configuration is used if any parameter is not set. 
But what are default parameters for rate_limit object?
In directus_settings table there is nothing.

Thank you

**Comment by dario30186** [comment]
@bjgajjar thank you for updating the doc.
But what about docker images ? 
Is it possible to define an environment variable in docker compose in order to override the rate limit object values? Or all people using docker are obliged to mount a volume for api.php file ?

**Comment by rijkvanzanten** [comment]
@WoLfulus is there a variable for the rate limit config currently?
