### ISSUE TITLE
Direct Link doesn't open Sidebar Panels

### ISSUE THREAD

**Issue by MentalGear** [directus/docs#221]
A direct doc link, for example, https://docs.directus.io/configuration/flows/operations.html doesn't open the corresponding sidebar panel, which would be really helpful for orientation and context - especially since there are also no breadcrumbs.

**Comment by rijkvanzanten** [comment]
I think this is more a bug/enhancement for VitePress rather than our docs 🙂 @brc-dd would you like me to re-report this under VitePress, or is this a known bug/enhancement? I looked at the open Issues, but didn't catch this.

**Comment by brc-dd** [comment]
Yeah, this is a bug. We have this functionality, but it looks like that auto expand thing is not triggering on the initial load (probably need to change some watch with watchEffect there).

**Comment by rijkvanzanten** [comment]
Closed in favor of https://github.com/vuejs/vitepress/pull/1361
