### ISSUE TITLE
db:update for 6.4.0 is not complete

### ISSUE THREAD

**Issue by dlaprade** [directus/docs#23]
Steps taken:
1. Backed up DB
2. Update directus source
3. Execute: php bin/directus db:upgrade
4. Bounce instance

Noticed:
1. 'select' no longer valid, looks like replaced by 'dropdown'
2. 'textinput' no longer valid, looks like replaced by 'text-input'
3. table: directus-ui was not removed during upgrade:
     https://github.com/directus/directus/releases/tag/6.4.0

This is not a complete list because I have not had time test every field.

Is the 'db:upgrade' going to handle the move from 6.3 -> 6.4?

**Comment by WellingGuzman** [comment]
Thanks for this report @dlaprade.

I will fix this today, yes, it should do it, I just missed it.

**Comment by WellingGuzman** [comment]
Closed by https://github.com/directus/directus/commit/d720d1bddeb75d3609cc7483ce5681a167d43c0a
