### ISSUE TITLE
Install: Add nginx configuration information

### ISSUE THREAD

**Issue by wellingguzman** [directus/docs#23]
Update the NGINX setup instructions: https://github.com/directus/docs-v7/blob/master/api/admin-guide/setup-nginx.md

**Comment by benhaynes** [comment]
Is this done? What else needs to happen here? @WellingGuzman 

https://docs.directus.io/advanced/server-setup.html#nginx

**Comment by WellingGuzman** [comment]
This one is not done. It needs to create the nginx configuration for Directus 7. The one in the documentation is for Directus 6.

**Comment by WellingGuzman** [comment]
I added the configuration example, but it needs more testing to see if it properly working. I believe the uploads location blocks isn't working together at the moment.

**Comment by harikt** [comment]
https://github.com/directus/docs/pull/134 hope the PR can fix the issue.

**Comment by benhaynes** [comment]
I'd like to add that NGINX is not "officially" supported and we can't vouch for the stability/functionality of this NGINX config. Please let us know if you're experiencing issues with it! :)
