### ISSUE TITLE
Broken/wrong link on "custom operations" page

### ISSUE THREAD

**Issue by sup2007** [directus/docs#231]
Broken (or wrong behavior) link on page https://docs.directus.io/extensions/operations.html 

> ## Custom Operations
> Custom Operations allow you to create new types of steps for flows. 
> [Learn more about Operations](https://docs.directus.io/getting-started/glossary.html#operations)

`#operations` hash (and content) missing on [target page](https://docs.directus.io/getting-started/glossary.html)

**Comment by br41nslug** [comment]
Thanks for letting us know! 😃
