### ISSUE TITLE
Cannot get around "Couldn't reach API" 

### ISSUE THREAD

**Issue by WebShapedBiz** [directus/docs#232]
Hi.
I'm on DigitalOcean managing all kinds of stuff, from WP, OctoberCMS, and CockpitCMS (PHP) to Strapi (NodeJS) but I just couldn't get this installation to work.
The Ubuntu 18.04 based LAMP is OK, every component works, but I always end up with a login screen saying "Couldn't reach API".
I've tried on-line documentation and your docx files attached in one of the posts here, to see if I have missed something, but I couldn't find anything that could give "Wellcome to Directus - Install" page.

Any ideas would be greatly appreciated.

Cheers.

**Comment by rijkvanzanten** [comment]
Make sure you have all the requirements on the server: https://docs.directus.io/getting-started/setup-checklist.html#checklist

Closing this as it's not a specific issue in the docs we can change
