### ISSUE TITLE
Webhooks vs Web Hooks

### ISSUE THREAD

**Issue by mvhirsch** [directus/docs#235]
Hi,

I was just exploring Hooks and noticed a duplication of the topic "Webhooks" and "Web Hooks".
They both describe the same, so I think they can safely be merged.

![Screenshot from 2019-11-15 10-32-36](https://user-images.githubusercontent.com/573047/68932826-ae0e9680-0793-11ea-9128-aeb299892837.png)

* https://docs.directus.io/extensions/hooks.html#web-hooks
* https://docs.directus.io/extensions/hooks.html#webhooks

greets from Austria,
Michael

**Comment by rijkvanzanten** [comment]
Good catch Michael! We also just added support for webhooks through the admin interface in the upcoming V8 so I'll dive in and update the docs :)
