### ISSUE TITLE
Custom User Role Menu - Incorrect Example

### ISSUE THREAD

**Issue by philleepflorence** [directus/docs#240]
## What is expected
Creating a custom menu using the example for collections should work.

## What is observed
Newly created links lead to a fatal error - No Project Found!

## Steps to Reproduce
1. Go to - https://docs.directus.io/guides/roles.html#creating-roles
2. Use the example to create a custom menu for a role.
3. Click on the link.

## Possible Solution
The project is needed for all links to collections.
`"path": "/collections/movies"` should be `"path": "/{{ project name }}/collections/movies"`

**Comment by benhaynes** [comment]
@rijkvanzanten — is this an issue with the Docs example, or the way the nav override is coded? I was just using the nav override and it was working fine (with the Docs example) other than the two tickets I opened.

**Comment by rijkvanzanten** [comment]
It's the docs example. The nav override allows you to add custom links, the one in the docs miss the project key in the path, which doesn't work in real life use

**Comment by philleepflorence** [comment]
Correct @rijkvanzanten ... the project key is missing in the example.
