### ISSUE TITLE
Files endpoint changed in v8

### ISSUE THREAD

**Issue by inta** [directus/docs#243]
I'm not sure wether this is a documentation issue, as the API is claimed to be stable, but I'll post it here because it did change already.

You should be able to add files by posting something like this:
```
{
  "filename": "image.jpg",
  "data": "<base64-content>"
}
```
to ```/[project]/files``` but now you have to post:
```
{
  "filename_disk": "image.jpg",
  "filename_download": "image.jpg",
  "data": "<base64-content>"
}
```
Should the documentation be updated or should that not have happened at all?

**Comment by rijkvanzanten** [comment]
The docs should('ve) be(en) updated
