### ISSUE TITLE
Describe "full_url" in File Object

### ISSUE THREAD

**Issue by benhaynes** [directus/docs#249]
I find it pretty crazy that something this important doesn't exist in our Docs at all. If the creator of Directus can't find/use this information, then certainly no one else will. We can't say the Docs are our single source of truth in regards to an API spec until they are reasonably complete/accurate.

Someone on this technical team needs to take on the task of auditing the API reference in its entirety to make sure we have a full listing of endpoints, each with example requests/responses, each supported param, and links to the proper error codes and data objects.

Anyone with a proper understanding of the API want to take this on? @directus/team

**Comment by rijkvanzanten** [comment]
Ref: this is the /files nested `data` response (see https://demo.directus.io/thumper/files)

```json
...
  "data": {
    "full_url": "https://demo.directus.io/uploads/thumper/originals/a88c3b72-ac58-5436-a4ec-b2858531333a.jpg",
    "url": "/uploads/thumper/originals/a88c3b72-ac58-5436-a4ec-b2858531333a.jpg",
    "thumbnails": [
      {
        "url": "https://demo.directus.io/thumper/assets/pnw7s9lqy68048g0?key=directus-small-crop",
        "relative_url": "/thumper/assets/pnw7s9lqy68048g0?key=directus-small-crop",
        "dimension": "64x64",
        "width": 64,
        "height": 64
      }
    ],
    "embed": null
  }
...
```

**Comment by rijkvanzanten** [comment]
Added in new api reference
