### ISSUE TITLE
Add theme chooser

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/docs#25]
So you can switch between dark/light mode.

This should be resolved when moving to VitePress, as that includes such a toggle out of the box.

**Comment by erondpowell** [comment]
> So you can switch between dark/light mode.
> 
> This should be resolved when moving to VitePress, as that includes such a toggle out of the box.

In VitePress, the toggle is setup in `config.js` and the colors for dark/light mode are just CSS classes.
Would this be a subset of the larger task, "customize CSS in VitePress"?

**Comment by erondpowell** [comment]
@rijkvanzanten 

Since we have the toggle, remaining work seems like a subset of the larger "Customize all CSS in VitePress" task.
Should we go ahead and close this issue?

**Comment by rijkvanzanten** [comment]
Lets just leave this open until vitepress branch is merged 👍🏻

**Comment by erondpowell** [comment]
Closed with #42
