### ISSUE TITLE
It would be great to see some explanation about JWT expiration on documentation

### ISSUE THREAD

**Issue by ahuseyn** [directus/docs#250]
# 🚀 Feature request

### Description
In documentation there is one sentence about JWT expiration:

> However, the tokens expire really quickly and you need to login using a users credentials to retrieve it. 

I am wondering if we have any solution to deal with JWT expiration or is there exact time period for JWT validity?

### Describe the solution you'd like
It would be good to see if we have any option to change JWT token expiration time. Is it possible to extend JWT expiration? 

### Describe alternatives you've considered
It is a big issue because sdk-js version 6 is not working properly and we can't use cookie mode auth effectively.

**Comment by rijkvanzanten** [comment]
Added note on jwt expiration in the new api reference
