### ISSUE TITLE
Add note about updating to DigitalOcean installation instructions

### ISSUE THREAD

**Issue by andgar2010** [directus/docs#252]
Check my own digitalOcean server 1 Click Install, but this version you have is 8.2.0. I want to upgrade to the latest version of Directus. Searching the documentation has explained how to upgrade from git or manual FTP, but it has not explained how to upgrade on digitalOcean. 

I don't know if it's correct to update Directus via the DigitalOcean console "/var/directus"?

I don't want to damage my current DigitalOcean project. :grimacing: 😨

**Comment by andgar2010** [comment]
Update from DigitalOcean:
1. Access SSH or Console Web of DigitalOcean to Server Directus.
2. Access folder `cd /&& cd var/directus`
3. Update version latest of Directus on GIT
Thanks for Bhargav Rao. Source: [Git Checkout Latest Tag](https://stackoverflow.com/a/22857288)
```
# Get new tags from remote
git fetch --tags

# Get latest tag name
latestTag=$(git describe --tags `git rev-list --tags --max-count=1`)

# Checkout latest tag
git checkout $latestTag
``` 

PD: 
I found a bug for update.
8.2.0 -> 8.3.1 (FAILED ERROR)
8.3.1 -> 8.2.0 (OK. SUCCESS RECOVED)
8.2.0 -> 8.3.0 -> 8.3.1 (OK. WORKED)

**Comment by rijkvanzanten** [comment]
@andgar2010 Is that bug the same as https://github.com/directus/directus/issues/2525?

**Comment by andgar2010** [comment]
> @andgar2010 Is that bug the same as [directus/directus#2525](https://github.com/directus/directus/issues/2525)?
@rijkvanzanten It's not the same mistake. The update from 8.2.0 -> 8.3.1 outputs an error warning that there are no correct load components.

**Comment by andgar2010** [comment]
But I found a component select bug not correctly showing label in v8.3.1, because I upgraded from v8.2.0.

http://{{SERVER_API}}/admin/#/{{PROJECT}}/users/1

Select Role 
**Directus 8.2.0**
![image](https://user-images.githubusercontent.com/19521054/71692456-ea17ae00-2d77-11ea-8f1e-fc13e3621c61.png)

**Directus 8.3.1**
![image](https://user-images.githubusercontent.com/19521054/71692615-6ad6aa00-2d78-11ea-97c5-3c774408292a.png)

**Comment by andgar2010** [comment]
[Bug no correct label Role on Select on V8.3.1 for update form v8.2.0](https://github.com/directus/app/issues/2380#issue-544749559)
