### ISSUE TITLE
Docs: Reference > Directus Dashboards

### ISSUE THREAD

**Issue by erondpowell** [directus/docs#26]
**While browsing system collections with the api, I noticed we don't have an API reference doc for dashboards.**

https://user-images.githubusercontent.com/62306630/176761383-81a9f2fa-9cfa-4886-b25b-94dc2d477f55.mov

**Comment by erondpowell** [comment]
@directus/team Do we need this at all? Or should I close it?

**Comment by rijkvanzanten** [comment]
@erondpowell Yes we do need it, and no don't close it 🙂

**Comment by rijkvanzanten** [comment]
Linear: DOCS-19
