### ISSUE TITLE
Document forcePathStyle env variable for S3 storage driver

### ISSUE THREAD

**Issue by azrikahar** [directus/docs#265]
Since directus/directus#16825 and directus/directus#17081, the `forcePathStyle` flag for S3 storage driver are now required to be `STORAGE_<location>_FORCE_PATH_STYLE` instead of `STORAGE_<location>_S3_FORCE_PATH_STYLE`.

**Comment by rijkvanzanten** [comment]
Fixed in 49e0929de3b886bff4d9dee9595a6097fe5fff96
