### ISSUE TITLE
Projects vs Multitenancy

### ISSUE THREAD

**Issue by WebShapedBiz** [directus/docs#270]
Hi.
I need some clarification regarding Projects. I'm afraid that Directus Projects are not Multitenancy, as it is suggested in the docs. Aside from the login page issue, where each user can see all the tenants, there is a bigger problem in the dashboard.
I have several Projects created on my DigitalOcean droplet and I've created a non-admin user inside my Project-1. **When logged in, that particular user shouldn't:**

- be able to see the Project switcher at all

- be able to select the Project-2 and Project-3 since that user doesn't belong there

- be thrown out of the dashboard, to the login page, when selecting the Project-2 or Project-3. This user doesn't have an account in those projects so how can they log in there?

I can understand that Super-admins can and probably must switch between the Projects and for that reason this feature is needed and more than welcomed, but for regular users? Shouldn't multitenancy separate accounts to the point where they are unaware of each other?
Or am I getting this completely wrong? 

Thank you for your time and effort.

Cheers.

**Comment by benhaynes** [comment]
Hi @WebShapedBiz — this is configurable. Each project config file has the option to be private, in which case it will not show up in the global login or project switcher.

https://docs.directus.io/guides/projects.html#private-projects

We're happy to discuss an intuitive and secure way to link users across different projects, but I wanted to point out how our multinenancy works.

**Comment by rijkvanzanten** [comment]
I believe the OP has been addressed with the ability to make projects private from each other. Happy to discuss multitenancy further [on Slack](https://directus.chat)!

**Comment by WebShapedBiz** [comment]
Thank you both @benhaynes @rijkvanzanten for your input, I've missed that information in the docs, my bad.
