### ISSUE TITLE
Broken "Learn more about the Extension Architecture" - link

### ISSUE THREAD

**Issue by gianpesto** [directus/docs#271]
Hi, i was reading about custom extensions on [this page](https://docs.directus.io/extensions/#architecture-explanation) and the link below is broken.

<img width="576" alt="grafik" src="https://user-images.githubusercontent.com/12595753/72719172-9e3a7680-3b77-11ea-91bb-0337f0330542.png">

**Comment by rijkvanzanten** [comment]
Good catch!
