### ISSUE TITLE
Recipe not working

### ISSUE THREAD

**Issue by lasseklein** [directus/docs#276]
The recipe for making a hierarchy suggests creating a field called "parent_id" as a number first, and then create a tree view field called children.

https://docs.directus.io/cookbook/data-models/build-a-content-hierarchy.html#explanation

When I tried this, I could not select the parent_id, but if I create the tree view field first and then simply enter the name parent_id as the foreign key name, it works.

**Comment by rijkvanzanten** [comment]
I believe this was a bug in the core platform that was since fixed 🙂 

https://github.com/directus/directus/issues/16692
