### ISSUE TITLE
Is link broken "database mirroring"?

### ISSUE THREAD

**Issue by andgar2010** [directus/docs#277]
I consulted the documentation, found a link, but it has no information "database mirroring" related to the [link](https://docs.directus.io/guides/database.html#database-mirroring). Is the link broken or will the next version be implemented?

![image](https://user-images.githubusercontent.com/19521054/72856311-2740d300-3c88-11ea-8966-53ce0140eaa2.png)

![image](https://user-images.githubusercontent.com/19521054/72856279-11331280-3c88-11ea-8416-004f4a61dacd.png)

**Comment by benhaynes** [comment]
I'm confused... the link on our website is working. Could you clarify the problem?

**Comment by benhaynes** [comment]
The info was in the sections below the title, but I added an intro to make this clearer.

https://docs.directus.io/guides/database.html#database-mirroring
