### ISSUE TITLE
What is the best way to associate users to users?

### ISSUE THREAD

**Issue by kevinmamaqi** [directus/docs#279]
Hi,

I have a user role called boss and a user role called employee. I want to retrieve a list of employees when the user with role boss is logged-in. Is that possible? If so, how?

**Comment by benhaynes** [comment]
Hey @kevinmamaqi — you'll need to be a bit more specific. Are these employees _assigned_ to a specific boss? Are you trying to do this in the API? Item browse page? Item detail page? Are these actual Directus users, or your own users collection? More info would let us help...

Also, GitHub is mostly for bug reports and feature requests... questions should go to StackOverflow or our Slack community. Just a heads up. 😊

**Comment by kevinmamaqi** [comment]
Sorry for that, I will use slack or stackoverflow from now on. Regarding this specific question:

I have created two roles:
- Boss
- Employ

I was wondering if it is possible to extend the Boss user to add an array of Employ IDs, or assign them somehow. Perhaps I do need to use Collections for this purpose, I don't know what is the best way to perform this relationship in Directus, if I were to use just MySQL I would extend the BOSS table with an array of EMPLY ids. I didn't want to create a collection to relate them seems a bit of overdoing it.

**Comment by rijkvanzanten** [comment]
It's currently not possible to extend Directus' internal collections with custom fields (eg adding a m2o 'boss' field to `directus_users`). This is high on our "want to have" feature list though, so hopefully this answer is outdated in a couple weeks 🙂

**Comment by benhaynes** [comment]
As Rijk said, the only way to do this is as of now is with custom collections/tables.

Although, the system collections _should_ allow you to add new fields if you do it directly in the database (creating the field, then setting it up in `directus_fields`. Although this is **not**officially supported yet. We'll be formalizing this soon and adding a way to do it through the App GUI.
