### ISSUE TITLE
Make Template Email

### ISSUE THREAD

**Issue by Rifqi-Irfansyah** [directus/docs#280]
How if I want to add email template with name created_items, like in example:sync with external

**Comment by Rifqi-Irfansyah** [comment]
![image](https://user-images.githubusercontent.com/96564588/216216734-a6a0ac7a-bc6b-47f3-bb3d-95976302559a.png)
how to add template

**Comment by rijkvanzanten** [comment]
I believe this is more a question for https://directus.chat than a bug in the docs 🤔 Happy to reopen if I'm mistaken ✌🏻
