### ISSUE TITLE
Layout Calendar on Directus 8.4.0?

### ISSUE THREAD

**Issue by andgar2010** [directus/docs#281]
Version Directus 8.4.0

Hello, 
I found out about Calendar layout feature of Directus on [twitter](https://twitter.com/directus/status/1092808106789212161), however I researched the documentation to implement calendar layout in our project Directus 8, but it has no information. I don't know what I did wrong. 
Please Help. 

Thank you

**Comment by r0b78** [comment]
How to auto-fill the date, when you press the add button
![image](https://user-images.githubusercontent.com/22716876/75100127-83508d00-558f-11ea-9f4f-24bbc1f7189d.png)

**Comment by Nitwel** [comment]
Sadly, this is not possible in the current version of directus but we are already working on a long therm solution for such problems.
