### ISSUE TITLE
Remove the documented CACHE_SYSTEM_TTL default value

### ISSUE THREAD

**Issue by YenTheFirst** [directus/docs#282]
### Describe the Bug

The config docs state that `CACHE_SYSTEM_TTL` has a default value of `10m` (https://docs.directus.io/self-hosted/config-options.html#cache). However, it appears that this environment variable does not actually have a default value (https://github.com/directus/directus/blob/main/api/src/env.ts#L225-L233)

Because `CACHE_SCHEMA` defaults to `true`, `CACHE_STORE` defaults to `memory`, and `CACHE_SYSTEM_TTL` defaults to `undefined`, it appears to be the case that the default behavior of directus, when deployed load-balanced with default configuration, is that any schema change is only recognized by one node, indefinitely, until the other nodes are restarted.

### To Reproduce

1. Deploy directus with 2 nodes behind a load balancer, and default config
2. on one node, add a new field to the table
3. perform a graphql query asking for the new field

### Errors Shown

About 50% of the time, the query will succeed. The other 50% of the time, it will fail.

If this test is re-run, but with an explicit value set for `CACHE_SYSTEM_TTL`, then queries will fail for about the duration of the cache system TTL, and then after the TTL will succeed 100% of the time.

### What version of Directus are you using?

9.13

### What version of Node.js are you using?

16.18.1

### What database are you using?

postgres 10

### What browser are you using?

N/A

### How are you deploying Directus?

docker on k8s

**Comment by azrikahar** [comment]
Resolved by #299
