### ISSUE TITLE
Available option Relationships One to One?

### ISSUE THREAD

**Issue by andgar2010** [directus/docs#284]
Hi,

what is the best practice for my following problem.

I have example three tables: product, event and invoice.

| Product_ID | Product_Quantity | Product_Name | Invoice_ID |
|------------|------------------|--------------|------------|
| 1          | 10               | aaa          | 1          |
| 2          | 5                | bbb          | 4          |
| 3          | 7                | ccc          | 5          |

| Event_ID | Event_Place | Invoice_ID |
|----------|-------------|------------|
| 1        | abc         | 2          |
| 2        | def         | 3          |
| 3        | ghi         | 6          |

| Invoice_ID | Invoice_Date | Invoice_Status |
|------------|--------------|----------------|
| 1          | 2020-01-01   | Canceled       |
| 2          | 2020-01-01   | Refund         |
| 3          | 2020-01-03   | Pending        |
| 4          | 2020-01-08   | Canceled       |
| 5          | 2020-01-10   | Canceled       |
| 6          | 2020-01-15   | Pending        |

Table **Product** or **Event** capture a relationship between **Invoice** and therefore have a one-to-one relationship with both tables. 

Because I can't find an option ONE TO ONE. but I don't know what else to do is the best FIELD for? 
ONE_TO_ONE, MANY_TO_ONE, ONE_TO_MANY, MANY_TO_MANY ?

**Comment by benhaynes** [comment]
A one-to-one (O2O) is basically the same as a many-to-one (M2O) depending on the data you save. For your data model, I would make...

* `product.invoice` a M2O to `invoice.id`
* `event.invoice` a M2O to `invoice.id`

Technically this would allow you to create items where multiple products/events could point to the same invoice, but that shouldn't really be an issue. And if it is, you can write custom logic (eg: event hook or custom interface) to enforce that.

**Comment by benhaynes** [comment]
Just to clear things up!

https://docs.directus.io/guides/relationships.html#one-to-one

**Comment by andgar2010** [comment]
Thank you for additional info on documentation. 🙂
