### ISSUE TITLE
How to get the count of nested items?

### ISSUE THREAD

**Issue by KULTI1995** [directus/docs#286]
![image](https://user-images.githubusercontent.com/14282128/73578244-72749600-447f-11ea-9dfd-0acd03be91e2.png)

How to get the count of nested items?
Instead of downloading an id and iterating, I'd rather just get the amount.

**Comment by rijkvanzanten** [comment]
You can add the `?meta=total_count` [meta parameter](https://docs.directus.io/api/query/meta.html) to get the counts.

**Comment by KULTI1995** [comment]
![image](https://user-images.githubusercontent.com/14282128/73581873-07c95780-448b-11ea-82c4-117340a7fa5b.png)
I want to get a number of related_news,for each parent.

**Comment by rijkvanzanten** [comment]
There's no way to do that right now. Feel free to open a feature request on the API repo though
