### ISSUE TITLE
Add SSO error codes

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/docs#30]

**Comment by rijkvanzanten** [comment]
@bjgajjar could you add these while you're looking at / going through the SSO flow? 🙂

**Comment by bjgajjar** [comment]
@rijkvanzanten - As per my knowledge, `SSO` error codes are the same as the `Auth` error code. So let me know still it needs to be added!

**Comment by rijkvanzanten** [comment]
Shouldn't there be errors for sso specific errors like "invalid callback token" and things like that?

**Comment by bjgajjar** [comment]
TBH, I didn't find something like that :( Still will check it again.

**Comment by rijkvanzanten** [comment]
It could be that they don't exist right now! I think there are a couple things that might happen in SSO that are specific for SSO

**Comment by rijkvanzanten** [comment]
Added this to the api reference
