### ISSUE TITLE
Use mermaid to generate schemas and workflow pictures

### ISSUE THREAD

**Issue by jooola** [directus/docs#305]
I propose to use [Mermaid.js](https://mermaid-js.github.io/mermaid/) to build and generate schemas and workflows. This should prevent us to store picture in the repository as files, and generate them on the fly.

Another way to store them is to encode the code that describe the schema and ship it as picture:
```
[![](https://mermaid.ink/img/eyJjb...NlfQ)](https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb...NlfQ)
```

[![](https://mermaid.ink/img/eyJjb2RlIjoiZ3JhcGggVERcblxuQVtTY2hlbWFdIC0tPkIoRW5jb2RlZCBzY2hlbWEpXG5CIC0tPiBDKEdlbmVyYXRlZCBwaWN0dXJlIGxpbmspXG5DIC0tPiBEKEVtYmVkIG1hcmtkb3duIHBpY3R1cmUpXG4iLCJtZXJtYWlkIjp7InRoZW1lIjoiZGVmYXVsdCJ9LCJ1cGRhdGVFZGl0b3IiOmZhbHNlfQ)](https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggVERcblxuQVtTY2hlbWFdIC0tPkIoRW5jb2RlZCBzY2hlbWEpXG5CIC0tPiBDKEdlbmVyYXRlZCBwaWN0dXJlIGxpbmspXG5DIC0tPiBEKEVtYmVkIG1hcmtkb3duIHBpY3R1cmUpXG4iLCJtZXJtYWlkIjp7InRoZW1lIjoiZGVmYXVsdCJ9LCJ1cGRhdGVFZGl0b3IiOmZhbHNlfQ)

**Comment by rijkvanzanten** [comment]
I'm wondering if the added complexity and learning curve is worth the benefit.

We don't really spend any significant amount of time on those right now. I would even argue that learning to use that tool and styling it to fit the brand will take more time than we've ever spent creating the image ones in the first place 🤷‍♂

**Comment by rijkvanzanten** [comment]
@benhaynes 🔔

**Comment by benhaynes** [comment]
I've been the one generating these in sketch/figma, I think (for now) I'd rather them be more designed and accurate, then easy to create. But that's an interesting idea.

Also, I use these diagrams and wire frames in other presentation collateral, so it's useful to have the design and export control.
