### ISSUE TITLE
Add information about $create status

### ISSUE THREAD

**Issue by wellingguzman** [directus/docs#32]
Add information about the `$create` custom status. This is a custom permission for new item (on create).

**Comment by WellingGuzman** [comment]
I didn't find anything related to the `$create` custom status. I am talking about this [directus/api/issues/497](https://github.com/directus/api/issues/497)

**Comment by benhaynes** [comment]
Yeah, the Docs I linked to is for the App (workflow/interface), but we also need the API/technical side which talks about how `$create` is the value used by that workflow status.

**Comment by rijkvanzanten** [comment]
Added a technical explainer doc on what all the values are for permissions

https://github.com/directus/api/wiki/Permissions
