### ISSUE TITLE
Is it possible to make sums?

### ISSUE THREAD

**Issue by Lecquio** [directus/docs#332]
English is not my native language, I hope you can understand me.
I have a collection with a list of products and his price and I want to know if it's possible to add a field with the total sum of prices, in this or another collection.

Thanks in advance

**Comment by benhaynes** [comment]
You could create a custom interface that gets a sum of the data you're looking for — that would be the best option for now. We're adding something called "displays" in v9 (in a few weeks) that might have some basic operator logic for things like this... but that specific feature  might take longer to include.
