### ISSUE TITLE
API Endpoint problems

### ISSUE THREAD

**Issue by tmota** [directus/docs#342]
I'm new at directus and I need some help.

I installed directus via softaculous, a service provided by my shared host.
I manage to create a few collections and now I'm trying to make requests but I can't find out what I'm doing wrong because the only response I get in Postman is:
GET: https://urze.org/public/:urze/collections
`{
    "error": {
        "error": 8,
        "message": "API Environment Configuration Not Found: collections"
    }
}`

According to softaculous the directus version is 7.0.20 . I know that I'm using an older version!

Can somebody help me to figure it out what is wrong or point me to a forum where I can find someone to help me? Probably is something related with softaculous installation.

Thank you and stay safe

**Comment by benhaynes** [comment]
It's going to be hard for anyone to help with such an old version. I'd recommend asking the provider to update... or just install it via git/FTP yourself. Perhaps give StackOverflow or our Slack community a try:

https://directus.chat

**Comment by tmota** [comment]
thanks @benhaynes. I'm gona try to upgrade my existing directus to the last version.
