### ISSUE TITLE
hook item.delete kaputt

### ISSUE THREAD

**Issue by michapixel** [directus/docs#373]
I'm trying to hook into the delete event but none of that works:

```
   'item.create.coopusers:before' => function (array $data) {
      # WORKS
    },
    'item.create.coopusers:after' => function (array $data) {
      # WORKS TOO
    },
    //  ----------------------------------
    'item.delete.coopusers:before' => function (array $data) {
      # NADA
    },
    'item.delete.coopusers:after' => function (array $data) {
       # NIENTE
    }
```

Not even:
```
'item.delete' => function ($collection, $data) { }
```
this is in the latest (8.8.1) directus i think.
you should really add a cli command for that (version) :)

**Comment by michapixel** [comment]
i just saw that `'item.delete' => function ($collection, $data) { }` is called when i delete say a custom field under 
`admin/#/project/settings/collections/test`
🥴
nothing in the error log btw.

**Comment by michapixel** [comment]
Oooooh, now i see:

i tried "item.update[...]" now the action showed up with a status flag of delete. This tells me that the status field i was using upon this collection items was "blocking" the real delete action, what a pitty i couldn't find anything in the manual about this. but maybe i was blind. 

so i replaced the status-field with something custon (radios) and see what i got there: 
item.delete
fires up! yeah!
now i can hook into that action, because i need to manually delete items files, which is kind of strange, because it's related ...
At least i can now, but should'n the user/admin be asked if he also wants to delete related files/items ... 

Maybe i did something wrong in my thinking ... maybe someone can explain a little more detailed ... ?

**Comment by rijkvanzanten** [comment]
Sounds like you have a status field on the collection that is a soft delete status. That means it updates your status flag instead of deleting the whole item when the user hits delete
