### ISSUE TITLE
Failing to get directus running

### ISSUE THREAD

**Issue by LimpingTwerp** [directus/docs#375]
Dear community,

I tried to install directus on my centos7 machine. I followed the instructions as outlined, adding a virtual host, setting the permission and the owner, and, since it's Centos, taking care of SELinux permissions, too. 

Upon calling "http://127.0.0.1/ in my browser I get a response which simply spells:  "run();", to complete source being:

<?php

$app = require __DIR__ . '/../src/web.php';

$app->run();

Error log is empty, access log shows what you may think. I worked through the installtion issue checklist, checked for the php modules and such. Still no luck. Where could I get more detailed information about what went wrong?

All the best and thank you!

**Comment by rijkvanzanten** [comment]
@LimpingTwerp Sounds like your server isn't running PHP, but is returning it as plain text
