### ISSUE TITLE
Details of App $Store

### ISSUE THREAD

**Issue by benhaynes** [directus/docs#41]
We should have one place that describes all of the values we have in the Store. This will hopefully alleviate questions like this: https://github.com/directus/api/issues/528#issuecomment-433758050

eg: `this.$store.state.settings`

Do we have something like this somewhere @rijkvanzanten ?

**Comment by rijkvanzanten** [comment]
We don't have a document on it right now, but you can already inspect the whole thing using the Vue DevTools:

<img width="585" alt="image" src="https://user-images.githubusercontent.com/9141017/47656870-5f7d6280-db66-11e8-91be-0d737855a39d.png">

**Comment by benhaynes** [comment]
True! I guess all the naming is pretty self-explanatory. I will add a Doc (hopefully today) with all of these keys and a description so people can see them without installing.

**Comment by benhaynes** [comment]
https://github.com/directus/docs/commit/b248714c099cab9f81eabc3cf6f56b9251880041
