### ISSUE TITLE
Overwrite GET /

### ISSUE THREAD

**Issue by minasvisual** [directus/docs#45]
Hi, 

I not found what overwrite de / url to load my frontend app. if i change index.php name automatically stop woking. 
I tried change /src/endpoints/home with a file_get_contents method and had no success.

**Comment by WellingGuzman** [comment]
Hey @minasvisual, I did not understand the question.

If you are taking about the routing of the application. You need to have `mod_rewrite` enabled in your apache web server to make the routing works.

Take a look at https://github.com/directus/api/blob/master/public/.htaccess#L12 and let me know if that's what you are referring to.

**Comment by benhaynes** [comment]
I'm not sure about your question either, @minasvisual. I'll close this, but please let us know what you're trying to do and we'll help out!
