### ISSUE TITLE
VitePress: Spellchecker CI

### ISSUE THREAD

**Issue by erondpowell** [directus/docs#46]
> Maybe we can also explore [spellchecker-cli](https://www.npmjs.com/package/spellchecker-cli) as a git hook or github action. 🤔
> It was what I used when I made the PR https://github.com/directus/directus/pull/9553. It may be non-trivial to setup a dictionary at first (to "whitelist" words such as Directus, O2M, M2A etc), however the bright side is that'll come with the advantage of standardizing the letter casing for words/terms that have been discussed for a while.

@azrikahar I'm not sure if you want to work on this or just suggesting but I tagged you as an assignee.

**Comment by azrikahar** [comment]
Drafted PR #52 for this 👍 Would you mind checking out the PR, run `npm run spellcheck`, and resolve the remaining warnings?

Just as a quick guide, when we run that command, it should say it's `Spellchecking 102 files...`. Once it's done, it'll log out in the format of "File path" and the warnings found with each file:

![Ny3PNvAr7H](https://user-images.githubusercontent.com/42867097/180130947-118478c4-26d3-4133-82c9-52f6c85d13e7.png)

In the above example, `self-hosted/installation/ubuntu.md` contains 2 warnings. `3:1-3:13` denotes the `DigitalOcean` term is in Line 3 Column 1-13.

To resolve it, we can add words/terms into the `dictionary.txt` file (should be in the root of this project after you checkout the PR). It is also possible to do regexes such as `[Dd]irectus` to match both `Directus` which is used generally and `directus` used in command examples.

![WindowsTerminal_kokGQ6v1Zh](https://user-images.githubusercontent.com/42867097/180131290-a6e47390-eeb6-4429-9862-887d540db217.png)

I've tried to resolved a bunch of them so now there's exactly 600 left! 😄 

---

Just a heads up, there seems to be a false positive for cases such as `<span mi icon>delete</span> delete` where it thinks it's a repetition error as `delete delete`, so we'll need to see how to best resolve that, but I believe most of the current warnings are inconsistencies in terms of letter casing for terms/brands so let's tackle those first.
