### ISSUE TITLE
Send Mail public error

### ISSUE THREAD

**Issue by minasvisual** [directus/docs#46]
HI. 

When a try send email from frontend (with no login) an error (Address in mailbox given [] does not comply with RFC 2822, 3.6.2.), cause the function bellow not return user mail and name. I think need to find email on config file to set from smtp. 
I fixed set from manually.
src/core/directus/Mail
```
protected function getFrom()
    {
        /** @var Acl $acl */
        $acl = $this->container->get('acl');

        return [
            $acl->getUserEmail() => $acl->getUserFullName()
        ];
    }
```

**Comment by WellingGuzman** [comment]
Are you trying to send an email without being authenticated? Because the mail `/mail` endpoint must be used with an valid authenticated user.

I open a ticket to throw an exception when a public request is made to the `/mail` endpoint. https://github.com/directus/api/issues/566
