### ISSUE TITLE
'Create Admin User' doc inconsistent Option flag: '-t' vs '-T'

### ISSUE THREAD

**Issue by hal869** [directus/docs#49]
@

https://docs.directus.io/api/admin/configure-with-script.html#create-admin-user

```
Create Admin User

$ bin/directus install:install -e <admin-email> -p <admin-password> -t <project-title>
```

is inconsistent with Options table
```
-t 	Token of the Directus user (Default: admin_token)
-T 	Title of the project (Default: Directus)
```

which is intended in the 'Create Admin User' ?  The instruction and the table value should match.

**Comment by WellingGuzman** [comment]
Thanks @hal869,

I fixed the problem, `t` is actually for the project title and `T` for the user token.

**Comment by tassoman** [comment]
as option for the command `bin/directus install:config` and `bin/directus install:database` project name is -N 

What about using *-P* for all the commands? I guess *-p* is taken for password.

**Comment by WellingGuzman** [comment]
@tassoman the issue here is that project is a name that was recently implemented, it used to be environment name, instance name, and now it's project name, and because it probably will always be "something" name, I kept using the `-N` instead.

**Comment by benhaynes** [comment]
We will be keeping the "project"  name, so we can commit to that. Not sure if this is a breaking change or not, but if `-P` is the better flag then we can use it.

Thoughts @WellingGuzman?

**Comment by WellingGuzman** [comment]
Better name will depends on preference, either one for me is fine. Changing this is a breaking chance, and it's not an critical bug, so I don't see the reason to change it now.
