### ISSUE TITLE
Where are the API docs?

### ISSUE THREAD

**Issue by suntrop** [directus/docs#5]
When I click the "VIEW API ENDPOINTS" button the website the link http://getdirectus.com/docs/api gets redirected to http://getdirectus.com/docs/getting-started/what-is-directus

**Comment by WellingGuzman** [comment]
Hi @suntrop, can you point me where's that button that has the wrong link? in the meantime here is the correct url: http://getdirectus.com/api/overview/api-overview (Work in Progress)

**Comment by suntrop** [comment]
I was talking about the link directly on the homepage (http://getdirectus.com middle of the page).

Thanks for the new link. I couldn't find another link to that page. 

This page is more interesting for me :-) and was what I was looking for. Thanks!

**Comment by WellingGuzman** [comment]
@suntrop I fixed the link on the home page.

Any question you may have don't hesitate to ask.
