### ISSUE TITLE
Hi-Fi images for the Data Model PR

### ISSUE THREAD

**Issue by erondpowell** [directus/docs#51]
Hi Fi images for `configuration > data-model.md` and `configuration > data-model > relationships.md` 
Required in order to complete PR https://github.com/directus/docs/pull/23

**Comment by benhaynes** [comment]
@erondpowell — can you clarify (or remind me) what we wanted to add here?

**Comment by rijkvanzanten** [comment]
@benhaynes We figured you might wanted to do the final versions of any graphics we wanted to add to the docs, so for now, we opted to add placeholder images for all the visual art on the data model pages:

https://deploy-preview-23--directus-docs.netlify.app/configuration/data-model/
https://deploy-preview-23--directus-docs.netlify.app/configuration/data-model/relationships/

(Although that being said, I actually weirdly kinda like the hand drawn style in here, it feels very supportive, like a buddy showing you how things work on the back of napkin, but I digress)

**Comment by erondpowell** [comment]
> (Although that being said, I actually weirdly kinda like the hand drawn style in here, it feels very supportive, like a buddy showing you how things work on the back of napkin, but I digress)

I am a huge fan of hand-drawn diagrams. Like Rijk points out, they take a certain amount of psychological pressure off. The heir of "seriousness and formality" is dropped, lowering a learner's Affective Filter.
But I also digress.... 🤠  HI-Fi images look more "professional".
(tbh, we could also do a *hi-fi hand-drawn*)

**Comment by benhaynes** [comment]
I also, like these hand-drawing ones... and am fine using this style! I think we'd want to clean them up to a standard format though. Rijk, thoughts on Excalidraw? Some things I'd like to address:

* Color palette (and primary, not red)
* Consistent text/type sizes
* Consistent border weight / radius
* Thoughtful layouts (eg: the second "schemas" one seems a bit scattered)

Beyond that, this page is feeling pretty long, but maybe it will be better when we have the "page headings" ToC on the right pane?

**Comment by rijkvanzanten** [comment]
Excalidraw would be great to make these in actually! That would make sure we can make them consistent, and store them in a format that allows us to save/reimport them for later edits 🙂 

I think using excalidraw will take care of the first three points. As for the thoughtful layouts, I think that's gonna be on a case by case basis.

> Beyond that, this page is feeling pretty long, but maybe it will be better when we have the "page headings" ToC on the right pane?

Agreed. VitePress upgrade takes care of that as it creates the toc on the right. Other than that, that one particular data model page is very much a "beginning to end" walkthrough of what a data model is and how it generally works, so not really a page where you'd have to go to find a specific bit of information (it's more of a piece you'd read from start to finish, so the length might not matter as much)

**Comment by benhaynes** [comment]
Agree on all points. Let's get a spec mocked up in Excalidraw and then we can generate once we agree on that.

**Comment by erondpowell** [comment]
Another point: Are we officially done with the inline `[[toc]]`?
Want me to remove all those in favor of the right-hand table of contents? (i vote yes for this)

**Comment by erondpowell** [comment]
> Agree on all points. Let's get a spec mocked up in Excalidraw and then we can generate once we agree on that.

Ben you want to do this? or want me to do it?
I'm also down to redo this lo-fi stuff in excalidraw, then hand it off to your for polish.

**Comment by rijkvanzanten** [comment]
@erondpowell Feel free to start it and we can tweak from there 👍🏻 Excalidraw doesn't really do a whole lot of fine design stuff (it's hand drawn style after all), so hopefully the only edits that are needed are just small organizational things.
