### ISSUE TITLE
How to set logo in v7?

### ISSUE THREAD

**Issue by sebj54** [directus/docs#56]
I read this documentation: https://docs.directus.io/app/admin/global-settings.html.

In there, I can see this about logo:

> Logo – If you would like to use your own logo you can upload it here. Specifications:
>     Dimensions – 200px wide and 60px tall
>     Format – PNG or SVG
>     Color – White foreground with a transparent background

It is not written the logo format. Should it be an absolute URL? Can it be a local file like in v6?

Thanks for your help about this :)

**Comment by benhaynes** [comment]
I believe that was copied from the v6 Docs (when we did have a way to update custom logos). We're working on re-implementing that feature... just need to squash a few more bugs first. 

We'll update the Docs in the meantime!

**Comment by rijkvanzanten** [comment]
This has been updated to project_logo, project_foreground, and project_background since. All of which are in directus_settings
