### ISSUE TITLE
External Storage

### ISSUE THREAD

**Issue by erondpowell** [directus/docs#6]
https://github.com/directus/directus/issues/7960

Explain how to configure external storage more clearly.

**Comment by erondpowell** [comment]
@rijkvanzanten At a glance, this looks like it is not a "code" problem, but more of a troubleshooting discussion.
Perhaps we should move this to discussions and wait to link it in to the docs.

**Comment by rijkvanzanten** [comment]
Works for me!

**Comment by rijkvanzanten** [comment]
Linear: DOCS-7
