### ISSUE TITLE
doc says JWTs are encrypted

### ISSUE THREAD

**Issue by beac0n** [directus/docs#62]
In https://directus.github.io/api/#tokens the documentation says:

> These tokens follow the JWT spec and contain the user id, type of token (auth), and an expiration date in the payload, which is **encrypted** with a secret key.

The JWT is not encrypted, but signed. The data, which a JWT contains, can be decoded here: https://jwt.io/

**Comment by rijkvanzanten** [comment]
Fair enough!

**Comment by beac0n** [comment]
The devil is in the detail ;-)
