### ISSUE TITLE
Cloud Rate Limits

### ISSUE THREAD

**Issue by erondpowell** [directus/docs#63]
Update cloud docs to reflect new rate limit details:
https://discord.com/channels/725371605378924594/1001471892537999401

**Comment by w0kyj** [comment]
New policies are ready and go live today/tomorrow (Aug 01 - 02, 2022)

Standard:
- General Purpose: 25 requests per second per node per IP
- Performance: 50 requests per second per node per IP

Enterprise:
- 100 requests per second per node per IP

NOTE: the limits are additive and load balanced over the nodes.

Example:
Client with 2 Standard performance nodes would get 100 requests per second per IP (eg 50 * 2 nodes = 100)

**Comment by w0kyj** [comment]
@erondpowell ^^

**Comment by erondpowell** [comment]
@w0kyj What about rate limits on Community?
