### ISSUE TITLE
Remove Smooth scrolling from the Docs.

### ISSUE THREAD

**Issue by makote** [directus/docs#68]
The scroll animation in the API docs makes the sidebar menu unusable. It takes way to long to scroll while learning to use the API. 

This might be a VUE issue and makes the API docs unusable in FF. 

Browser: Firefox (Latest)
OS: OSX Mojave

**Comment by rijkvanzanten** [comment]
Yeah weird huh. We didn't activate it, so I think it's something in VuePress itself

**Comment by sikko** [comment]
This is pretty frustrating indeed. Glad someone filed the issue

**Comment by rijkvanzanten** [comment]
Turns out this is a problem in VuePress itself!

https://github.com/vuejs/vuepress/commit/5b0cdcf5b8792b7d25e159fed836867675fd2b58

**Comment by benhaynes** [comment]
Yup! That's it... seems like it will  be fixed soon.

**Comment by rijkvanzanten** [comment]
vuepress alpha.27 should include a fix. We upgraded to this version but it didn't propagate over the build yet. Lemme see what's up with that

**Comment by rijkvanzanten** [comment]
I forced a deploy and that seemed to have killed the smooth scroll. I don't think that's VuePress' intention, but hey it beats the insanely slow scroll 🎉

**Comment by makote** [comment]
This is back on the live docs

**Comment by benhaynes** [comment]
Nooooooooooo....

**Comment by benhaynes** [comment]
Was it something I did, @rijkvanzanten ?

**Comment by benhaynes** [comment]
Not sure who/what fixed this... but it's fixed again!

**Comment by rijkvanzanten** [comment]
> Not sure who/what fixed this... but it's fixed again!

+1 for using alpha versions 😄
