### ISSUE TITLE
Extensions

### ISSUE THREAD

**Issue by benhaynes** [directus/docs#69]
This was a TODO in the code, I'm moving it here for better visibility and so we don't much-up the Docs. Ideally these should be broken-out into many individual tickets.

* Link to Install Wiki/Docs for getting up and running
* How to create a new one (write from scratch, copy existing)
* Maybe explain that the `value` is the important variable to save to? (should be obvious, but might help)
* How to work with validation, conditionals for styling, etc
* Options! What are they? How to set them, how to fetch/use them in the code
* Include link to full styleguide (Google Doc for now)
* Maybe explain the Core components they can use? (eg: `v-input` and `v-dropdown`)
* Quick explanation of each item in meta.json
* Rules for using/including external libraries (size, how to, license, etc)
* Can they write code tests for these interfaces?
* "Building" the interfaces... is this needed? When does it happen?
* `npm` commands... for some reason aI can't find them :confused:
* End with quick info on where/how to properly submit an interface PR to us

**Comment by rijkvanzanten** [comment]
I believe we have this, and we have the separate extension builder to facilitate most of this
