### ISSUE TITLE
Missing guide how to write a custom endpoint with joined tables

### ISSUE THREAD

**Issue by df7** [directus/docs#70]
### Dear Directus team,
I've set up Directus, created all the collections I wanted and filled them with data.
I used the [docs](https://docs.directus.io/extensions/custom-endpoints.html#creating-custom-endpoints) to create a new endpoint which also works now.

My questions for which I unfortunately could not find answers in the docs:

**How do I query tables within the ecosystem of a Directus extension?**
I guess that `\Directus\Database\TableGatewayFactory::create()` in connection with `Zend\Db\TableGateway\TableGateway` can be used for this. It's just annoying to have to reverse engineer the existing code without any hints in the docs. Links to the right external resources would be really nice here.

**How do I query tables with inner joins, left outer joins, right outer joins in Directus extension PHP code?**
There are no docs on this topic.

**How do I GROUP a joined result set within Directus and how do I use aggregate functions in SELECT?**

**If I join five tables, how do I implement an ACL check for each of the tables [for the current user]?**

**Comment by benhaynes** [comment]
We're restructuring the Docs now (releasing Friday) and can add some additional info and external links to show how to connect to data from within Directus.

@WellingGuzman — perhaps you could add a `data.md` here: https://github.com/directus/docs/tree/restructure/advanced/api

**Comment by df7** [comment]
@benhaynes Thank you for your reply! Any update on this?

**Comment by WellingGuzman** [comment]
> **How do I query tables within the ecosystem of a Directus extension?**
> I guess that `\Directus\Database\TableGatewayFactory::create()` in connection with `Zend\Db\TableGateway\TableGateway` can be used for this. It's just annoying to have to reverse engineer the existing code without any hints in the docs. Links to the right external resources would be really nice here.

You can use Zend DB TableGateway to fetch all data, the only disadvantage is that default core hooks won't be executed. I added some notes on how to create those in here: https://github.com/directus/docs/blob/master/api/data.md#fetching-data-within-hooks-and-endpoints

> 
> **How do I query tables with inner joins, left outer joins, right outer joins in Directus extension PHP code?**
> There are no docs on this topic.
> 
> **How do I GROUP a joined result set within Directus and how do I use aggregate functions in SELECT?**
> 
> **If I join five tables, how do I implement an ACL check for each of the tables [for the current user]?**

You can use the Zend DB TableGateway join method, but you can't use alongside Directus `fetchData` method. (See the documentation link above)

**Comment by df7** [comment]
@WellingGuzman     
I implemented the following four lines in a custom endpoint function as described in the linked doc but Acl does not seem to work at all.

$container = \Directus\Application\Application::getInstance()->getContainer();
$dbConnection = $container->get('database');
$acl = $container->get('acl');
$userId = $acl->getUserId();
$hasPermission = $acl->canRead('directus_users');

I am calling my the custom endpoint with:
_http://directus.local/_/custom/endpoint-name?access_token=my_static_token_
With _my_static_token_ being the value in directus_users.token for my user.
What I get is that the $userId is null every time. Hence I never have permissions to any protected collection.

However, if I use the Items query API to query the same collection using the same token, I do receive the correct dataset. [This call works fine: _http://directus.local/_/items/my-custom-collection?access_token=my_static_token_ ]

Either the docs are missing a hint, why the class core/Directus/Permissions/Acl.php does not translate my access token into the correct userId or this is just a bug.
Looking forward to your insights.

**Comment by WellingGuzman** [comment]
That's an expected behavior, all the custom endpoints has not authorization, the the user never gets authenticated based on the `access_token` query string, so there's not permission to anything.

I will close this ticket as the main request was addressed.

We can keep the conversation if you think there's should be an option for enable the authorization layer for custom endpoints (or a custom endpoint). If you do, and it seems like a nice feature, we could open a new ticket in the API.

**Comment by rijkvanzanten** [comment]
> If you do, and it seems like a nice feature, we could open a new ticket in the API.

I +1 this, I think it would be great (and in certain cases needed) to be able to limit the use of an endpoint based on the user.

Alternatively, maybe the API can make the user ID based on the token available to the endpoint code? That way, the implementation itself can check for whatever and grant or deny access

**Comment by rijkvanzanten** [comment]
>  I am heavily relying on custom endpoints, because almost all of my GET requests require SQL JOINs and **I can't join multiple tables using the Item API at all**.

Can you clarify why not? You can set up relational interfaces that allow you to fetch data from multiple collections nested. Is that system not flexible enough for your use case?

**Comment by df7** [comment]
> Can you clarify why not? You can set up relational interfaces that allow you to fetch data from multiple collections nested. Is that system not flexible enough for your use case?
I must admit I haven't looked into nested queries with `*.*`  before. I just tested them and it seems to work fine for one of my queries with a join 👍 
Coming from a Lumen REST API background, however, I still have security worries due to filters being provided on the client side. Once I give every of my users access to the directus powered API, they will be able to pull and change data of other users within the system as well. And that's something they should not be able to do. 
Example: Assume, that you develop a simple ToDo app. Users only see their own todo items because you have set filters _on the client side_, but a registered attacker will find both his own access token and the API and fire some requests without these filters.

Maybe I'm just misunderstanding the purpose of Directus. Directus is a user-friendly suite of tools to set up and manage the database but it's unsuitable as a secure REST API framework and I wanted to have both.


> > When a user requests a new access token, isn't that token already personalized?
> 
> Yes it is! You can extract the user ID from the token.

Great! So how complicated is it to extract the user ID, name etc. on the server side within the custom endpoint handler?

**Comment by siryan2** [comment]
I came across the same problem and "solved" it by extending the 'custom' route definition in web.php with the 'auth' middleware. After that I can use TableGatewayFactory and all services descripted in https://github.com/directus/docs/blob/master/api/data.md#fetching-data-within-hooks-and-endpoints.
Does these change cause an security risk?

// cc: @df7
