### ISSUE TITLE
How to add embeds to Directus Files

### ISSUE THREAD

**Issue by benhaynes** [directus/docs#75]
This does not have any info:

https://docs.directus.io/api/reference.html#upload-file

Does the API still support adding embeds (eg: YouTube, Vimeo)? How is this accomplished through the  API?

**Comment by WellingGuzman** [comment]
I added a note on how to add embedded YouTube and Vimeo video to Directus files.

Ref: https://github.com/directus/docs/blob/master/api/reference.md#using-supported-embedded-urls

I opened this ticket to add information on how to add custom/new embed providers. (https://github.com/directus/docs/issues/76)
