### ISSUE TITLE
Add an example on how to use static tokens

### ISSUE THREAD

**Issue by ianjakubek** [directus/docs#78]
The docs on how to use static tokens are extremely limited so please either add an example or some more documentation. Thanks
https://docs.directus.io/api/reference.html#static-tokens

**Comment by WellingGuzman** [comment]
Hey @ianjakubek,

There are three example on how to use static tokens: Using http header, query string, and auth basic. 

What are you looking for what is missing in the documentation? Let me know I will add an example as soon as possible.

**Comment by ianjakubek** [comment]
Thank you for the quick response, I'm trying to find how to set up static tokens for certain users. I seem to only be able to find how to use them.
Am I understanding something wrong here?

**Comment by rijkvanzanten** [comment]
okay https://github.com/directus/docs/commit/201881d461237db48e890d94754db663ed70ef9f#diff-8c5e91a0b277a2024d06f03fb8dea779

🙂

**Comment by rijkvanzanten** [comment]
(It'll take a couple minutes before it will appear on the website docs)

**Comment by ianjakubek** [comment]
Wow thanks! Love the application btw

**Comment by rijkvanzanten** [comment]
Thanks @ianjakubek :)
