### ISSUE TITLE
[Preview] Algolia DocSearch modal get's triggered twice

### ISSUE THREAD

**Issue by hanneskuettner** [directus/docs#82]
When using the shortcut `Cmd+K` the search overlay get's triggered (and rendered) twice.

![CleanShot 2024-12-22 at 21 44 34@2x](https://github.com/user-attachments/assets/2f2055c4-d6ef-4b09-b9c3-854305ac6eae)

**Comment by hanneskuettner** [comment]
This seems to only happen on the deployed Vercel preview but not in the local dev mode. I can't build the docs locally because of the Nuxt UI Pro license key missing.

**Comment by rijkvanzanten** [comment]
I'm not seeing this on the prod directus.io/docs though 🤔

**Comment by hanneskuettner** [comment]
Me neither. Weird. Let's close it for now.
