### ISSUE TITLE
How to add 3rd party packages in suite installation

### ISSUE THREAD

**Issue by ybelenko** [directus/docs#83]
Thanks for Directus Suite v7.0.13

I've installed it with:
```bash
$ git clone https://github.com/directus/directus.git
```

Current `vendor` folder contains `symfony/validator` but I would prefer different package for data validation. Is there any guide on how to install packages via Composer in suite installation?

Do I have to clone API and App repos separately if I need to extend dependencies?

**Comment by benhaynes** [comment]
@rijkvanzanten @WellingGuzman 

Any recommendations for this? Could we add a section to the Docs for this please?

**Comment by WellingGuzman** [comment]
The `directus/directus` repository is missing the `composer.json`, we must add it.

As a workaround, you can do this:

> 1. Copy [`composer.json`](https://raw.githubusercontent.com/directus/api/master/composer.json) to your root directory.
> 2. Add your packages
> 3. Run `composer install` (to reinstall everything and regenerate the autoload)

**Comment by benhaynes** [comment]
@rijkvanzanten @WellingGuzman — is it worth adding this into the combined repo for this purpose?

**Comment by WellingGuzman** [comment]
Closed this ticket in favor of https://github.com/directus/directus/issues/2273

**Comment by WellingGuzman** [comment]
> @rijkvanzanten @WellingGuzman — is it worth adding this into the combined repo for this purpose?

I believe so, this way help people add new packages or reinstall everything with a given php version (_if that helps for something_).
