### ISSUE TITLE
Documentation Style Guide

### ISSUE THREAD

**Issue by erondpowell** [directus/docs#9]
Hey, I think it's about time we spin up a "Documentation Style Guide".
A single source of truth for these doc design decisions and the 'how to' manual for the team/community.

- [ ] Images
- [ ] Video
- [ ] Language: punctuation, grammar, etc.
- [ ] Document Types
- [ ] Useful Links

Do not link to sections on pages. 
Link to the page, and indicate the section.
This will avoid broken links.

**”Buttons”** and **Components**
The -, –, — situation (ask Ben)

The

**Comment by rijkvanzanten** [comment]
Linear: DOCS-9
