### ISSUE TITLE
How to create a hook to interface

### ISSUE THREAD

**Issue by benhaynes** [directus/docs#9]
How to create a hook to interface

**Comment by benhaynes** [comment]
Is this @rijkvanzanten  or @WellingGuzman ?

**Comment by rijkvanzanten** [comment]
I don't know enough about hooks.. I could throw something together based on the interface hook Welling build, but I think he's more equipped with this knowledge

**Comment by WellingGuzman** [comment]
All hooks are created equally the different is where to register them. I will close this in favor of #35, which will close when it explain how to create hooks from different places including interfaces.

Even though this ticket was open way before #35, that one include this one.

**Comment by WellingGuzman** [comment]
I added the a note on how to create hooks from interfaces, pages and as custom hooks here: https://github.com/directus/docs/blob/master/extensions/hooks.md#places-to-create-hooks
