### ISSUE TITLE
Unable to filter fields under M2A relationships using GraphQL

### ISSUE THREAD

**Issue by maximka1221** [directus/docs#93]
### Describe the Bug

Hello,
I cant seem to be able to query fields of objects nested inside a many-to-any relationship using the GraphQL API. (and there seems to be no related docs about how to do it)

As described [in the docs](https://docs.directus.io/reference/query.html#many-to-any-union-types), the full field path I need to use for filtering is `<m2a-field>:<collection-scope>.<field>` (for example `sections.item:headings.title`) but the colon (`:`) character is not valid in a GraphQL attribute name.

The following would be a valid JSON query to send to the REST api:
```json
{
    "sections": {
        "item:headings": {
            "title": {
                "_eq": "Section 1"
            }
        }
    }
}
```

Which would be equivalent to the following (invalid) GraphQL query:
```gql
query {
    articles(filter: {
        sections: {
            "item:headings": {  # Invalid
                title: {
                    _eq: "Section 1"
                }
            }
        }
    }): {
        id
    }
}
```

Is there any way to achieve this? If not, is the support for this planed?
Thanks!

### To Reproduce

1. Create 3 data models: `articles`, `headings` and `paragraphs`
2. Add a M2A relationship field named `sections` in `articles` that points to `headings` and `paragraphs`
3. Create an Article object that contains a Heading and Paragraph objects in its `sections` field
4. Try to query and filter the data using the GraphQL API

### What version of Directus are you using?

9.15.1

### What version of Node.js are you using?

16.16.0

### What database are you using?

Postgres 13

### What browser are you using?

GraphQL Playground

### How are you deploying Directus?

Docker

**Comment by azrikahar** [comment]
> but the colon (`:`) character is not valid in a GraphQL attribute name

> Which would be equivalent to the following (invalid) GraphQL query

Understandably how it can be confused as such, but in the linked docs, the important bit for GraphQL in Many-To-Any is this sentence here: `"In GraphQL, this can be achieved using Union Types."`

There is an example on GraphQL Union Types (which is used to get items in M2A field) over here: https://docs.directus.io/reference/introduction.html#graphql

Additional example:

![chrome_ueAhAOQoIu](https://user-images.githubusercontent.com/42867097/184558729-b03e80ba-368d-422d-b524-733e743a0775.png)

So perhaps we should add a link to this section on that page to make it clearer.

---

However in regards to filtering the M2A items in GraphQL, I'm not sure if it's supported, but I'll defer to @rijkvanzanten on this.

**Comment by maximka1221** [comment]
Hi, thank you for your quick response!
Yes, I saw the part about field selection using unions, I was specifically speaking about filtering (sorry if I was not clear enough)

**Comment by maximka1221** [comment]
Hi @rijkvanzanten , can you please help with this?

**Comment by maximka1221** [comment]
NVM, I have found the following [comment in the code](https://github.com/directus/directus/blob/main/api/src/services/graphql/index.ts#L1079).
I have opened 2 PRs that implement this functionallity: [directus#15162](https://github.com/directus/directus/pull/15162), [docs#105](https://github.com/directus/docs/pull/105)

**Comment by rijkvanzanten** [comment]
Thanks @maximka1221! ❤️ I'll take a look as soon as a get a chance 🙂
