### ISSUE TITLE
More information about Hook class and locations

### ISSUE THREAD

**Issue by Steven-Harris** [directus/docs#94]
I just recently found out about this project and I am really looking forward using more. Setting up my collections was super easy and painless. However, when I start to configure Webhooks I hit a lot of issues. They're probably not real issues, I am just new to this project and I am probably messing things up. I had to read the source just to figure out what the docs were talking about. 

Here are somethings that would have helped me when setting up webhooks. 
 1. **Add locations of the files** The docs reference adding actions and filters to the hooks array config. However, it's unclear from the docs where that location is for new devs. After looking through the source, I figured out is was in config/api.php.

2. **Clearer implementation for Classes** I still can't figure out how use a Class instead of an inline function. The inline function works great but even when I copy/paste the CreateItemEvent from the docs, the server errors out. I add the action to the hooks array in the config. I have no idea where to put the php file so I put under `public/extensions/custom/hooks/somefolder`. Maybe that's the wrong place but I can't tell from the docs. I have also tried setting using a hook.php but got the same issue.

3. **Where to see errors/logs** I am new to using this project so this is probably available somewhere I just could find the logs to see where things where failing. I see there is a logs folder but I didn't see and errors in there even though the server was not responding

4. **More Samples** The samples in `public/extensions/custom/hooks` #35 were helpful but it would be great if there where more showing class implements for actions, multiple actions, etc. 

Addressing some of this ares might help new developers to the project, like me, get started. 

Thanks keep up the good work!

**Comment by hakkurishian** [comment]
I'm having the same issue.  Using the docker image which has an auto-created configuration file, it is very cumbersome to update the config file. From The docs, it isn't really clear to me if its possible to activate a web hook *outside* of the config file or not. In case it is, a placement in custom/hooks/webhook.php did not work out for me. I'm not sure if that is because of the hook failing ( referring to point 3 in the OP. Would greatly appreciate a doc improvement here since it makes getting started with docker extremely hard for me.

**Comment by benhaynes** [comment]
@directus/api-team — any thoughts? Can we get the docs (and/or code comments) updated so this is clear?

**Comment by rijkvanzanten** [comment]
I've moved the info on web hooks to the hooks file so it's clearer how / where to create them
