### ISSUE TITLE
500 errors and slow response times

### ISSUE THREAD

**Issue by br41nslug** [directus/docs#95]
I was browsing the API Reference and noticed the response times between clicking a link and the docs UI updating felt like half a second to a second. And on opening the dev panel noticed a ton of `500` errors that had around half a second of request time which would explain the slow UI updates if these requests are blocking somehow.

Are these requests intentional and/or required? the requests look like they contain the full example code for some reason 🤔 should this not be done on the browsers end?

<img width="1080" alt="firefox_OhhCpyGqpj" src="https://github.com/user-attachments/assets/7d18c5eb-6869-4afb-bb87-5bc911d9fb68" />

**Comment by rijkvanzanten** [comment]
https://github.com/directus/docs/pull/98 might fix this, lets wait and see

**Comment by rijkvanzanten** [comment]
Resolved in #99
