### ISSUE TITLE
Create Article with Troubleshooting Steps

### ISSUE THREAD

**Issue by benhaynes** [directus/docs#97]
Many developers that are less experienced with Directus (or development in general) run into issues installing Directus. A step-by-step guide for troubleshooting would be useful, where each step goes further into the install and points you to fixes if you get stuck along the way.

Here are some ideas... but I'd love to hear other thoughts! Once we have most steps here we can write this into the Docs or on Medium.

1. Server Requirements — Does your server meet the [minimum Directus requirements](https://docs.directus.io/advanced/requirements.html)?
    * Apache 2
    * PHP 7.1+
    * MySQL 5.2+
1. Are all required PHP Extensions enabled on your server?
    * `pdo`, `mysql`, `curl`, `gd`, `fileinfo`, `mbstring`, and `xml`
1. Is `mod_rewrite` enabled for `.htaccess` files?
1. Is the root directory for the Directus API set to the `/public` directory?
1. Is the directory ownership set to the user the web server is running under? 
    Usually the user is `www-data` — eg: `sudo chown -R www-data:www-data /var/www/api`
1. Do the following `files/folders` have write permission?
    * `/logs`
    * `/public/uploads` (or your configured upload directory)
1. Are you using the [latest release of Directus](https://github.com/directus/directus/releases)?
    * If you upgraded, did you run the migration script?
1. Did you install or create the API configuration file?
1. Did you install or create the App configuration file?
1. Did you get a `pong` response from the `/ping` server endpoint?
1. Are you using the correct API project URL?
1. Did you check your logs?
    * Directus logs
    * Apache logs
    * PHP logs
    * MySQL logs
1. Did you check GitHub for an open issue similar to yours?

If all of the above fails, you should:

1. Ask for help on the #support channel of our Community Slack
1. Post a question on StackOverflow
1. If this truly seems like a `bug` (not a configuration problem) then report it on GitHub Issues

**Comment by benhaynes** [comment]
@rijkvanzanten @WellingGuzman — Can you guys think of any other useful troubleshooting steps we can add in here? What common install/setup issues have you heard a lot of?

**Comment by uchilaka** [comment]
I'm working on a draft of `setup-checklist.md`. Proposal: link to the `setup-checklist.md` guide at the top of `installation.md` to provide users with the tips (you outlined above). Would this be helpful? I'll put a PR out once I've added the update for your review

**Comment by uchilaka** [comment]
Put out a PR of the draft for this: https://github.com/directus/docs/pull/157. Will continue to flesh out `setup-checklist.md`. As I went through the document, it seemed it we would likely need a similar doc for:
- OS-level / Unix
- Docker
- <all the other modes of installation>

**Comment by benhaynes** [comment]
Reviewing now! Thanks @uchilaka!

**Comment by rijkvanzanten** [comment]
All the points in the OP are in the mentioned setup-checklist.md file, that has since been merged.
